document.createElement("canvas").getContext||function(){function S(){return this.context_||(this.context_=new A(this))}function T(a,b,c){var e=J.call(arguments,2);return function(){return a.apply(b,e.concat(J.call(arguments)))}}function K(a){return(""+a).replace(/&/g,"&amp;").replace(/"/g,"&quot;")}function L(a){a.namespaces.g_vml_||a.namespaces.add("g_vml_","urn:schemas-microsoft-com:vml","#default#VML");a.namespaces.g_o_||a.namespaces.add("g_o_","urn:schemas-microsoft-com:office:office","#default#VML");
a.styleSheets.ex_canvas_||(a=a.createStyleSheet(),a.owningElement.id="ex_canvas_",a.cssText="canvas{display:inline-block;overflow:hidden;text-align:left;width:300px;height:150px}")}function U(a){var b=a.srcElement;switch(a.propertyName){case "width":b.getContext().clearRect();b.style.width=b.attributes.width.nodeValue+"px";b.firstChild.style.width=b.clientWidth+"px";break;case "height":b.getContext().clearRect(),b.style.height=b.attributes.height.nodeValue+"px",b.firstChild.style.height=b.clientHeight+
"px"}}function V(a){a=a.srcElement;a.firstChild&&(a.firstChild.style.width=a.clientWidth+"px",a.firstChild.style.height=a.clientHeight+"px")}function B(){return[[1,0,0],[0,1,0],[0,0,1]]}function r(a,b){for(var c=B(),e=0;3>e;e++)for(var f=0;3>f;f++){for(var d=0,g=0;3>g;g++)d+=a[e][g]*b[g][f];c[e][f]=d}return c}function M(a,b){b.fillStyle=a.fillStyle;b.lineCap=a.lineCap;b.lineJoin=a.lineJoin;b.lineWidth=a.lineWidth;b.miterLimit=a.miterLimit;b.shadowBlur=a.shadowBlur;b.shadowColor=a.shadowColor;b.shadowOffsetX=
a.shadowOffsetX;b.shadowOffsetY=a.shadowOffsetY;b.strokeStyle=a.strokeStyle;b.globalAlpha=a.globalAlpha;b.font=a.font;b.textAlign=a.textAlign;b.textBaseline=a.textBaseline;b.arcScaleX_=a.arcScaleX_;b.arcScaleY_=a.arcScaleY_;b.lineScale_=a.lineScale_}function N(a){var b=a.indexOf("(",3),c=a.indexOf(")",b+1),b=a.substring(b+1,c).split(",");4==b.length&&"a"==a.substr(3,1)?alpha=Number(b[3]):b[3]=1;return b}function C(a,b,c){return Math.min(c,Math.max(b,a))}function D(a,b,c){0>c&&c++;1<c&&c--;return 1>
6*c?a+6*(b-a)*c:1>2*c?b:2>3*c?a+6*(b-a)*(2/3-c):a}function E(a){var b=1,a=""+a;if("#"!=a.charAt(0))if(/^rgb/.test(a)){for(var b=N(a),a="#",c,e=0;3>e;e++)c=-1!=b[e].indexOf("%")?Math.floor(255*(parseFloat(b[e])/100)):Number(b[e]),a+=u[C(c,0,255)];b=b[3]}else if(/^hsl/.test(a)){a=b=N(a);h=parseFloat(a[0])/360%360;0>h&&h++;s=C(parseFloat(a[1])/100,0,1);l=C(parseFloat(a[2])/100,0,1);if(0==s)a=c=e=l;else{var e=0.5>l?l*(1+s):l+s-l*s,f=2*l-e,a=D(f,e,h+1/3);c=D(f,e,h);e=D(f,e,h-1/3)}a="#"+u[Math.floor(255*
a)]+u[Math.floor(255*c)]+u[Math.floor(255*e)];b=b[3]}else a=W[a]||a;return{color:a,alpha:b}}function X(a){switch(a){case "butt":return"flat";case "round":return"round";default:return"square"}}function A(a){this.m_=B();this.mStack_=[];this.aStack_=[];this.currentPath_=[];this.fillStyle=this.strokeStyle="#000";this.lineWidth=1;this.lineJoin="miter";this.lineCap="butt";this.miterLimit=1*q;this.globalAlpha=1;this.font="10px sans-serif";this.textAlign="left";this.textBaseline="alphabetic";this.canvas=
a;var b=a.ownerDocument.createElement("div");b.style.width=a.clientWidth+"px";b.style.height=a.clientHeight+"px";b.style.overflow="hidden";b.style.position="absolute";a.appendChild(b);this.element_=b;this.lineScale_=this.arcScaleY_=this.arcScaleX_=1}function O(a,b,c,e){a.currentPath_.push({type:"bezierCurveTo",cp1x:b.x,cp1y:b.y,cp2x:c.x,cp2y:c.y,x:e.x,y:e.y});a.currentX_=e.x;a.currentY_=e.y}function P(a,b){var c=E(a.strokeStyle),e=c.color,c=c.alpha*a.globalAlpha,f=a.lineScale_*a.lineWidth;1>f&&(c*=
f);b.push("<g_vml_:stroke",' opacity="',c,'"',' joinstyle="',a.lineJoin,'"',' miterlimit="',a.miterLimit,'"',' endcap="',X(a.lineCap),'"',' weight="',f,'px"',' color="',e,'" />')}function Q(a,b,c,e){var f=a.fillStyle,d=a.arcScaleX_,g=a.arcScaleY_,i=e.x-c.x,o=e.y-c.y;if(f instanceof v){var j=0,k=e=0,t=0,n=1;if("gradient"==f.type_){var j=f.x1_/d,c=f.y1_/g,p=a.getCoords_(f.x0_/d,f.y0_/g),j=a.getCoords_(j,c),j=180*Math.atan2(j.x-p.x,j.y-p.y)/Math.PI;0>j&&(j+=360);1.0E-6>j&&(j=0)}else p=a.getCoords_(f.x0_,
f.y0_),e=(p.x-c.x)/i,k=(p.y-c.y)/o,i/=d*q,o/=g*q,n=w.max(i,o),t=2*f.r0_/n,n=2*f.r1_/n-t;d=f.colors_;d.sort(function(a,b){return a.offset-b.offset});for(var g=d.length,p=d[0].color,c=d[g-1].color,i=d[0].alpha*a.globalAlpha,a=d[g-1].alpha*a.globalAlpha,o=[],m=0;m<g;m++){var r=d[m];o.push(r.offset*n+t+" "+r.color)}b.push('<g_vml_:fill type="',f.type_,'"',' method="none" focus="100%"',' color="',p,'"',' color2="',c,'"',' colors="',o.join(","),'"',' opacity="',a,'"',' g_o_:opacity2="',i,'"',' angle="',
j,'"',' focusposition="',e,",",k,'" />')}else f instanceof F?i&&o&&b.push("<g_vml_:fill",' position="',-c.x/i*d*d,",",-c.y/o*g*g,'"',' type="tile"',' src="',f.src_,'" />'):(f=E(a.fillStyle),b.push('<g_vml_:fill color="',f.color,'" opacity="',f.alpha*a.globalAlpha,'" />'))}function x(a,b,c){isFinite(b[0][0])&&isFinite(b[0][1])&&isFinite(b[1][0])&&isFinite(b[1][1])&&isFinite(b[2][0])&&isFinite(b[2][1])&&(a.m_=b,c&&(a.lineScale_=Y(Z(b[0][0]*b[1][1]-b[0][1]*b[1][0]))))}function v(a){this.type_=a;this.r1_=
this.y1_=this.x1_=this.r0_=this.y0_=this.x0_=0;this.colors_=[]}function F(a,b){if(!a||1!=a.nodeType||"IMG"!=a.tagName)throw new y("TYPE_MISMATCH_ERR");if("complete"!=a.readyState)throw new y("INVALID_STATE_ERR");switch(b){case "repeat":case null:case "":this.repetition_="repeat";break;case "repeat-x":case "repeat-y":case "no-repeat":this.repetition_=b;break;default:throw new y("SYNTAX_ERR");}this.src_=a.src;this.width_=a.width;this.height_=a.height}function y(a){this.code=this[a];this.message=a+": DOM Exception "+
this.code}var w=Math,i=w.round,G=w.sin,H=w.cos,Z=w.abs,Y=w.sqrt,q=10,m=q/2,J=Array.prototype.slice;L(document);var R={init:function(a){/MSIE/.test(navigator.userAgent)&&!window.opera&&(a=a||document,a.createElement("canvas"),a.attachEvent("onreadystatechange",T(this.init_,this,a)))},init_:function(a){for(var a=a.getElementsByTagName("canvas"),b=0;b<a.length;b++)this.initElement(a[b])},initElement:function(a){if(!a.getContext){a.getContext=S;L(a.ownerDocument);a.innerHTML="";a.attachEvent("onpropertychange",
U);a.attachEvent("onresize",V);var b=a.attributes;b.width&&b.width.specified?a.style.width=b.width.nodeValue+"px":a.width=a.clientWidth;b.height&&b.height.specified?a.style.height=b.height.nodeValue+"px":a.height=a.clientHeight}return a}};R.init();for(var u=[],d=0;16>d;d++)for(var z=0;16>z;z++)u[16*d+z]=d.toString(16)+z.toString(16);var W={aliceblue:"#F0F8FF",antiquewhite:"#FAEBD7",aquamarine:"#7FFFD4",azure:"#F0FFFF",beige:"#F5F5DC",bisque:"#FFE4C4",black:"#000000",blanchedalmond:"#FFEBCD",blueviolet:"#8A2BE2",
brown:"#A52A2A",burlywood:"#DEB887",cadetblue:"#5F9EA0",chartreuse:"#7FFF00",chocolate:"#D2691E",coral:"#FF7F50",cornflowerblue:"#6495ED",cornsilk:"#FFF8DC",crimson:"#DC143C",cyan:"#00FFFF",darkblue:"#00008B",darkcyan:"#008B8B",darkgoldenrod:"#B8860B",darkgray:"#A9A9A9",darkgreen:"#006400",darkgrey:"#A9A9A9",darkkhaki:"#BDB76B",darkmagenta:"#8B008B",darkolivegreen:"#556B2F",darkorange:"#FF8C00",darkorchid:"#9932CC",darkred:"#8B0000",darksalmon:"#E9967A",darkseagreen:"#8FBC8F",darkslateblue:"#483D8B",
darkslategray:"#2F4F4F",darkslategrey:"#2F4F4F",darkturquoise:"#00CED1",darkviolet:"#9400D3",deeppink:"#FF1493",deepskyblue:"#00BFFF",dimgray:"#696969",dimgrey:"#696969",dodgerblue:"#1E90FF",firebrick:"#B22222",floralwhite:"#FFFAF0",forestgreen:"#228B22",gainsboro:"#DCDCDC",ghostwhite:"#F8F8FF",gold:"#FFD700",goldenrod:"#DAA520",grey:"#808080",greenyellow:"#ADFF2F",honeydew:"#F0FFF0",hotpink:"#FF69B4",indianred:"#CD5C5C",indigo:"#4B0082",ivory:"#FFFFF0",khaki:"#F0E68C",lavender:"#E6E6FA",lavenderblush:"#FFF0F5",
lawngreen:"#7CFC00",lemonchiffon:"#FFFACD",lightblue:"#ADD8E6",lightcoral:"#F08080",lightcyan:"#E0FFFF",lightgoldenrodyellow:"#FAFAD2",lightgreen:"#90EE90",lightgrey:"#D3D3D3",lightpink:"#FFB6C1",lightsalmon:"#FFA07A",lightseagreen:"#20B2AA",lightskyblue:"#87CEFA",lightslategray:"#778899",lightslategrey:"#778899",lightsteelblue:"#B0C4DE",lightyellow:"#FFFFE0",limegreen:"#32CD32",linen:"#FAF0E6",magenta:"#FF00FF",mediumaquamarine:"#66CDAA",mediumblue:"#0000CD",mediumorchid:"#BA55D3",mediumpurple:"#9370DB",
mediumseagreen:"#3CB371",mediumslateblue:"#7B68EE",mediumspringgreen:"#00FA9A",mediumturquoise:"#48D1CC",mediumvioletred:"#C71585",midnightblue:"#191970",mintcream:"#F5FFFA",mistyrose:"#FFE4E1",moccasin:"#FFE4B5",navajowhite:"#FFDEAD",oldlace:"#FDF5E6",olivedrab:"#6B8E23",orange:"#FFA500",orangered:"#FF4500",orchid:"#DA70D6",palegoldenrod:"#EEE8AA",palegreen:"#98FB98",paleturquoise:"#AFEEEE",palevioletred:"#DB7093",papayawhip:"#FFEFD5",peachpuff:"#FFDAB9",peru:"#CD853F",pink:"#FFC0CB",plum:"#DDA0DD",
powderblue:"#B0E0E6",rosybrown:"#BC8F8F",royalblue:"#4169E1",saddlebrown:"#8B4513",salmon:"#FA8072",sandybrown:"#F4A460",seagreen:"#2E8B57",seashell:"#FFF5EE",sienna:"#A0522D",skyblue:"#87CEEB",slateblue:"#6A5ACD",slategray:"#708090",slategrey:"#708090",snow:"#FFFAFA",springgreen:"#00FF7F",steelblue:"#4682B4",tan:"#D2B48C",thistle:"#D8BFD8",tomato:"#FF6347",turquoise:"#40E0D0",violet:"#EE82EE",wheat:"#F5DEB3",whitesmoke:"#F5F5F5",yellowgreen:"#9ACD32"},I={},d=A.prototype;d.clearRect=function(){this.textMeasureEl_&&
(this.textMeasureEl_.removeNode(!0),this.textMeasureEl_=null);this.element_.innerHTML=""};d.beginPath=function(){this.currentPath_=[]};d.moveTo=function(a,b){var c=this.getCoords_(a,b);this.currentPath_.push({type:"moveTo",x:c.x,y:c.y});this.currentX_=c.x;this.currentY_=c.y};d.lineTo=function(a,b){var c=this.getCoords_(a,b);this.currentPath_.push({type:"lineTo",x:c.x,y:c.y});this.currentX_=c.x;this.currentY_=c.y};d.bezierCurveTo=function(a,b,c,e,f,d){f=this.getCoords_(f,d);a=this.getCoords_(a,b);
c=this.getCoords_(c,e);O(this,a,c,f)};d.quadraticCurveTo=function(a,b,c,e){a=this.getCoords_(a,b);c=this.getCoords_(c,e);e={x:this.currentX_+2/3*(a.x-this.currentX_),y:this.currentY_+2/3*(a.y-this.currentY_)};O(this,e,{x:e.x+(c.x-this.currentX_)/3,y:e.y+(c.y-this.currentY_)/3},c)};d.arc=function(a,b,c,e,f,d){var c=c*q,g=d?"at":"wa",i=a+H(e)*c-m,o=b+G(e)*c-m,e=a+H(f)*c-m,f=b+G(f)*c-m;i==e&&!d&&(i+=0.125);a=this.getCoords_(a,b);i=this.getCoords_(i,o);e=this.getCoords_(e,f);this.currentPath_.push({type:g,
x:a.x,y:a.y,radius:c,xStart:i.x,yStart:i.y,xEnd:e.x,yEnd:e.y})};d.rect=function(a,b,c,e){this.moveTo(a,b);this.lineTo(a+c,b);this.lineTo(a+c,b+e);this.lineTo(a,b+e);this.closePath()};d.strokeRect=function(a,b,c,e){var f=this.currentPath_;this.beginPath();this.moveTo(a,b);this.lineTo(a+c,b);this.lineTo(a+c,b+e);this.lineTo(a,b+e);this.closePath();this.stroke();this.currentPath_=f};d.fillRect=function(a,b,c,e){var f=this.currentPath_;this.beginPath();this.moveTo(a,b);this.lineTo(a+c,b);this.lineTo(a+
c,b+e);this.lineTo(a,b+e);this.closePath();this.fill();this.currentPath_=f};d.createLinearGradient=function(a,b,c,e){var f=new v("gradient");f.x0_=a;f.y0_=b;f.x1_=c;f.y1_=e;return f};d.createRadialGradient=function(a,b,c,e,f,d){var g=new v("gradientradial");g.x0_=a;g.y0_=b;g.r0_=c;g.x1_=e;g.y1_=f;g.r1_=d;return g};d.drawImage=function(a,b){var c,e,f,d,g,m,o,j;f=a.runtimeStyle.width;d=a.runtimeStyle.height;a.runtimeStyle.width="auto";a.runtimeStyle.height="auto";var k=a.width,t=a.height;a.runtimeStyle.width=
f;a.runtimeStyle.height=d;if(3==arguments.length)c=arguments[1],e=arguments[2],g=m=0,o=f=k,j=d=t;else if(5==arguments.length)c=arguments[1],e=arguments[2],f=arguments[3],d=arguments[4],g=m=0,o=k,j=t;else if(9==arguments.length)g=arguments[1],m=arguments[2],o=arguments[3],j=arguments[4],c=arguments[5],e=arguments[6],f=arguments[7],d=arguments[8];else throw Error("Invalid number of arguments");var n=this.getCoords_(c,e),p=[];p.push(" <g_vml_:group",' coordsize="',10*q,",",10*q,'"',' coordorigin="0,0"',
' style="width:',10,"px;height:",10,"px;position:absolute;");if(1!=this.m_[0][0]||this.m_[0][1]||1!=this.m_[1][1]||this.m_[1][0]){var r=[];r.push("M11=",this.m_[0][0],",","M12=",this.m_[1][0],",","M21=",this.m_[0][1],",","M22=",this.m_[1][1],",","Dx=",i(n.x/q),",","Dy=",i(n.y/q),"");var u=this.getCoords_(c+f,e),v=this.getCoords_(c,e+d);c=this.getCoords_(c+f,e+d);n.x=w.max(n.x,u.x,v.x,c.x);n.y=w.max(n.y,u.y,v.y,c.y);p.push("padding:0 ",i(n.x/q),"px ",i(n.y/q),"px 0;filter:progid:DXImageTransform.Microsoft.Matrix(",
r.join(""),", sizingmethod='clip');")}else p.push("top:",i(n.y/q),"px;left:",i(n.x/q),"px;");p.push(' ">','<g_vml_:image src="',a.src,'"',' style="width:',q*f,"px;"," height:",q*d,'px"',' cropleft="',g/k,'"',' croptop="',m/t,'"',' cropright="',(k-g-o)/k,'"',' cropbottom="',(t-m-j)/t,'"'," />","</g_vml_:group>");this.element_.insertAdjacentHTML("BeforeEnd",p.join(""))};d.stroke=function(a){for(var b={x:null,y:null},c={x:null,y:null},e=0;e<this.currentPath_.length;e+=5E3){var d=[];d.push("<g_vml_:shape",
' filled="',!!a,'"',' style="position:absolute;width:',10,"px;height:",10,'px;"',' coordorigin="0,0"',' coordsize="',10*q,",",10*q,'"',' stroked="',!a,'"',' path="');for(var m=e;m<Math.min(e+5E3,this.currentPath_.length);m++){0==m%5E3&&0<m&&d.push(" m ",i(this.currentPath_[m-1].x),",",i(this.currentPath_[m-1].y));var g=this.currentPath_[m];switch(g.type){case "moveTo":d.push(" m ",i(g.x),",",i(g.y));break;case "lineTo":d.push(" l ",i(g.x),",",i(g.y));break;case "close":d.push(" x ");g=null;break;
case "bezierCurveTo":d.push(" c ",i(g.cp1x),",",i(g.cp1y),",",i(g.cp2x),",",i(g.cp2y),",",i(g.x),",",i(g.y));break;case "at":case "wa":d.push(" ",g.type," ",i(g.x-this.arcScaleX_*g.radius),",",i(g.y-this.arcScaleY_*g.radius)," ",i(g.x+this.arcScaleX_*g.radius),",",i(g.y+this.arcScaleY_*g.radius)," ",i(g.xStart),",",i(g.yStart)," ",i(g.xEnd),",",i(g.yEnd))}if(g){if(null==b.x||g.x<b.x)b.x=g.x;if(null==c.x||g.x>c.x)c.x=g.x;if(null==b.y||g.y<b.y)b.y=g.y;if(null==c.y||g.y>c.y)c.y=g.y}}d.push(' ">');a?
Q(this,d,b,c):P(this,d);d.push("</g_vml_:shape>");this.element_.insertAdjacentHTML("beforeEnd",d.join(""))}};d.fill=function(){this.stroke(!0)};d.closePath=function(){this.currentPath_.push({type:"close"})};d.getCoords_=function(a,b){var c=this.m_;return{x:q*(a*c[0][0]+b*c[1][0]+c[2][0])-m,y:q*(a*c[0][1]+b*c[1][1]+c[2][1])-m}};d.save=function(){var a={};M(this,a);this.aStack_.push(a);this.mStack_.push(this.m_);this.m_=r(B(),this.m_)};d.restore=function(){this.aStack_.length&&(M(this.aStack_.pop(),
this),this.m_=this.mStack_.pop())};d.translate=function(a,b){x(this,r([[1,0,0],[0,1,0],[a,b,1]],this.m_),!1)};d.rotate=function(a){var b=H(a),a=G(a);x(this,r([[b,a,0],[-a,b,0],[0,0,1]],this.m_),!1)};d.scale=function(a,b){this.arcScaleX_*=a;this.arcScaleY_*=b;x(this,r([[a,0,0],[0,b,0],[0,0,1]],this.m_),!0)};d.transform=function(a,b,c,d,f,i){x(this,r([[a,b,0],[c,d,0],[f,i,1]],this.m_),!0)};d.setTransform=function(a,b,c,d,f,i){x(this,[[a,b,0],[c,d,0],[f,i,1]],!0)};d.drawText_=function(a,b,c,d,f){var m=
this.m_,d=0,g=1E3,r=0,o=[],j;j=this.font;if(I[j])j=I[j];else{var k=document.createElement("div").style;try{k.font=j}catch(t){}j=I[j]={style:k.fontStyle||"normal",variant:k.fontVariant||"normal",weight:k.fontWeight||"normal",size:k.fontSize||10,family:k.fontFamily||"sans-serif"}}var k=j,n=this.element_;j={};for(var p in k)j[p]=k[p];p=parseFloat(n.currentStyle.fontSize);n=parseFloat(k.size);j.size="number"==typeof k.size?k.size:-1!=k.size.indexOf("px")?n:-1!=k.size.indexOf("em")?p*n:-1!=k.size.indexOf("%")?
p/100*n:-1!=k.size.indexOf("pt")?n/0.75:p;j.size*=0.981;p=j.style+" "+j.variant+" "+j.weight+" "+j.size+"px "+j.family;n=this.element_.currentStyle;k=this.textAlign.toLowerCase();switch(k){case "left":case "center":case "right":break;case "end":k="ltr"==n.direction?"right":"left";break;case "start":k="rtl"==n.direction?"right":"left";break;default:k="left"}switch(this.textBaseline){case "hanging":case "top":r=j.size/1.75;break;case "middle":break;default:case null:case "alphabetic":case "ideographic":case "bottom":r=
-j.size/2.25}switch(k){case "right":d=1E3;g=0.05;break;case "center":d=g=500}b=this.getCoords_(b+0,c+r);o.push('<g_vml_:line from="',-d,' 0" to="',g,' 0.05" ',' coordsize="100 100" coordorigin="0 0"',' filled="',!f,'" stroked="',!!f,'" style="position:absolute;width:1px;height:1px;">');f?P(this,o):Q(this,o,{x:-d,y:0},{x:g,y:j.size});f=m[0][0].toFixed(3)+","+m[1][0].toFixed(3)+","+m[0][1].toFixed(3)+","+m[1][1].toFixed(3)+",0,0";b=i(b.x/q)+","+i(b.y/q);o.push('<g_vml_:skew on="t" matrix="',f,'" ',
' offset="',b,'" origin="',d,' 0" />','<g_vml_:path textpathok="true" />','<g_vml_:textpath on="true" string="',K(a),'" style="v-text-align:',k,";font:",K(p),'" /></g_vml_:line>');this.element_.insertAdjacentHTML("beforeEnd",o.join(""))};d.fillText=function(a,b,c,d){this.drawText_(a,b,c,d,!1)};d.strokeText=function(a,b,c,d){this.drawText_(a,b,c,d,!0)};d.measureText=function(a){this.textMeasureEl_||(this.element_.insertAdjacentHTML("beforeEnd",'<span style="position:absolute;top:-20000px;left:0;padding:0;margin:0;border:none;white-space:pre;"></span>'),
this.textMeasureEl_=this.element_.lastChild);var b=this.element_.ownerDocument;this.textMeasureEl_.innerHTML="";this.textMeasureEl_.style.font=this.font;this.textMeasureEl_.appendChild(b.createTextNode(a));return{width:this.textMeasureEl_.offsetWidth}};d.clip=function(){};d.arcTo=function(){};d.createPattern=function(a,b){return new F(a,b)};v.prototype.addColorStop=function(a,b){b=E(b);this.colors_.push({offset:a,color:b.color,alpha:b.alpha})};d=y.prototype=Error();d.INDEX_SIZE_ERR=1;d.DOMSTRING_SIZE_ERR=
2;d.HIERARCHY_REQUEST_ERR=3;d.WRONG_DOCUMENT_ERR=4;d.INVALID_CHARACTER_ERR=5;d.NO_DATA_ALLOWED_ERR=6;d.NO_MODIFICATION_ALLOWED_ERR=7;d.NOT_FOUND_ERR=8;d.NOT_SUPPORTED_ERR=9;d.INUSE_ATTRIBUTE_ERR=10;d.INVALID_STATE_ERR=11;d.SYNTAX_ERR=12;d.INVALID_MODIFICATION_ERR=13;d.NAMESPACE_ERR=14;d.INVALID_ACCESS_ERR=15;d.VALIDATION_ERR=16;d.TYPE_MISMATCH_ERR=17;G_vmlCanvasManager=R;CanvasRenderingContext2D=A;CanvasGradient=v;CanvasPattern=F;DOMException=y}();
//@ sourceMappingURL=excanvas.js.map