(function(v){function Y(w,h,va){var E,D,u,R,x,T,U;function ea(a){for(var d=[],b=0;b<a.length;++b){var c;if(a[b].data){c={};for(var e in a[b])c[e]=a[b][e]}else c={data:a[b]};d.push(c)}B=d;d=B.length;b=[];c=[];for(a=0;a<B.length;++a)e=B[a].color,null!=e&&(--d,"number"==typeof e?c.push(e):b.push(F(B[a].color)));for(a=0;a<c.length;++a)d=Math.max(d,c[a]+1);b=[];for(a=c=0;b.length<d;){e=j.colors.length==a?new J(100,100,100):F(j.colors[a]);var p=1+0.2*(1==c%2?-1:1)*Math.ceil(c/2);e.scale(p,p,p);b.push(e);
++a;a>=j.colors.length&&(a=0,++c)}for(a=d=0;a<B.length;++a)c=B[a],null==c.color?(c.color=b[d].toString(),++d):"number"==typeof c.color&&(c.color=b[c.color].toString()),c.lines=v.extend(!0,{},j.lines,c.lines),c.points=v.extend(!0,{},j.points,c.points),c.bars=v.extend(!0,{},j.bars,c.bars),null==c.lines.show&&!c.bars.show&&!c.points.show&&(c.lines.show=!0),null==c.shadowSize&&(c.shadowSize=j.shadowSize),c.xaxis||(c.xaxis=g.xaxis),1==c.xaxis?c.xaxis=g.xaxis:2==c.xaxis&&(c.xaxis=g.x2axis),c.yaxis||(c.yaxis=
g.yaxis),1==c.yaxis?c.yaxis=g.yaxis:2==c.yaxis&&(c.yaxis=g.y2axis),c.threshold||(c.threshold=j.threshold),c.subseries=null;var a=Number.POSITIVE_INFINITY,d=Number.NEGATIVE_INFINITY,G,f;for(G in g)g[G].datamin=a,g[G].datamax=d,g[G].min=j[G].min,g[G].max=j[G].max,g[G].used=!1;for(G=0;G<B.length;++G){b=B[G];b.datapoints={points:[],incr:2};var Z=b.data,q=b.datapoints.points,t=b.xaxis,H=b.yaxis,I=a,o=d,k=a,n=d,m,r,h,s=[];b.bars.show&&(b.datapoints.incr=3,s.push({d:0}));t.used=H.used=!0;c=b.datapoints.incr;
for(e=p=0;e<Z.length;++e,p+=c){h=Z[e];r=m=null;null!=Z[e]&&(m=h[0],r=h[1]);null!=m&&!isNaN(m=+m)?(m<I&&(I=m),m>o&&(o=m)):m=null;null!=r&&!isNaN(r=+r)?(r<k&&(k=r),r>n&&(n=r)):r=null;if(null==m||null==r)m=r=null;for(f=2;f<c;++f)q[p+f]=null==h[f]?s[f-2].d:h[f];q[p+1]=r;q[p]=m}b.bars.show&&(e="left"==b.bars.align?0:-b.bars.barWidth/2,b.bars.horizontal?(k+=e,n+=e+b.bars.barWidth):(I+=e,o+=e+b.bars.barWidth));t.datamin=Math.min(t.datamin,I);t.datamax=Math.max(t.datamax,o);H.datamin=Math.min(H.datamin,k);
H.datamax=Math.max(H.datamax,n);if(b.lines.show&&b.lines.steps){h=[];for(e=p=0;e<q.length;e+=c,p+=c)m=q[e],r=q[e+1],0<e&&null!=q[e-c]&&null!=m&&q[e-c+1]!=r&&(h[p]=m,h[p+1]=q[e-c+1],p+=c),h[p]=m,h[p+1]=r;b.datapoints.linespoints=h}if(b.threshold){t=v.extend({},b);H=v.extend({},b);t.datapoints={points:[],incr:c};H.datapoints={points:[],incr:c};H.color=b.threshold.color;I=b.threshold.below;o=t.datapoints.points;k=H.datapoints.points;for(e=0;e<q.length;e+=c)m=q[e],r=q[e+1],h=r<I?k:o,h.push(m),h.push(r);
if(b.lines.show){q=b.datapoints.linespoints||q;o=[];k=[];h=o;for(e=0;e<q.length;e+=c)m=q[e],r=q[e+1],n=h,null!=r&&(h=r<I?k:o),h!=n&&null!=m&&0<e&&null!=q[e-c]&&(p=(m-q[e-c])/(r-q[e-c+1])*(I-r)+m,n.push(p),n.push(I),h.push(null),h.push(null),h.push(p),h.push(I)),h.push(m),h.push(r);t.datapoints.linespoints=o;H.datapoints.linespoints=k}b.subseries=[t,H]}}}function fa(){function a(a,c){Y(a,c);da(a,c);xa(a,c);a==g.xaxis||a==g.x2axis?(a.p2c=function(c){return(c-a.min)*a.scale},a.c2p=function(c){return a.min+
c/a.scale}):(a.p2c=function(c){return(a.max-c)*a.scale},a.c2p=function(c){return a.max-c/a.scale})}for(var d in g)a(g[d],j[d]);ya();za();Aa()}function Y(a,d){var b=null!=d.min?+d.min:a.datamin,c=null!=d.max?+d.max:a.datamax;b==Number.POSITIVE_INFINITY&&(b=0);c==Number.NEGATIVE_INFINITY&&(c=1);if(0==c-b){var e=0==c?1:0.01;null==d.min&&(b-=e);if(null==d.max||null!=d.min)c+=e}else e=d.autoscaleMargin,null!=e&&(null==d.min&&(b-=(c-b)*e,0>b&&0<=a.datamin&&(b=0)),null==d.max&&(c+=(c-b)*e,0<c&&0>=a.datamax&&
(c=0)));a.min=b;a.max=c}function da(a,d){var b=(a.max-a.min)/("number"==typeof d.ticks&&0<d.ticks?d.ticks:a==g.xaxis||a==g.x2axis?K/100:L/60),c,e,p;if("time"==d.mode){var f={second:1E3,minute:6E4,hour:36E5,day:864E5,month:2592E6,year:525949.2*6E4};p=[[1,"second"],[2,"second"],[5,"second"],[10,"second"],[30,"second"],[1,"minute"],[2,"minute"],[5,"minute"],[10,"minute"],[30,"minute"],[1,"hour"],[2,"hour"],[4,"hour"],[8,"hour"],[12,"hour"],[1,"day"],[2,"day"],[3,"day"],[0.25,"month"],[0.5,"month"],[1,
"month"],[2,"month"],[3,"month"],[6,"month"],[1,"year"]];c=0;null!=d.minTickSize&&(c="number"==typeof d.tickSize?d.tickSize:d.minTickSize[0]*f[d.minTickSize[1]]);for(e=0;e<p.length-1&&!(b<(p[e][0]*f[p[e][1]]+p[e+1][0]*f[p[e+1][1]])/2&&p[e][0]*f[p[e][1]]>=c);++e);c=p[e][0];e=p[e][1];"year"==e&&(p=Math.pow(10,Math.floor(Math.log(b/f.year)/Math.LN10)),b=b/f.year/p,c=(1.5>b?1:3>b?2:7.5>b?5:10)*p);d.tickSize&&(c=d.tickSize[0],e=d.tickSize[1]);b=function(a){var b=[],c=a.tickSize[0],e=a.tickSize[1],d=new Date(a.min),
p=c*f[e];"second"==e&&d.setUTCSeconds(S(d.getUTCSeconds(),c));"minute"==e&&d.setUTCMinutes(S(d.getUTCMinutes(),c));"hour"==e&&d.setUTCHours(S(d.getUTCHours(),c));"month"==e&&d.setUTCMonth(S(d.getUTCMonth(),c));"year"==e&&d.setUTCFullYear(S(d.getUTCFullYear(),c));d.setUTCMilliseconds(0);p>=f.minute&&d.setUTCSeconds(0);p>=f.hour&&d.setUTCMinutes(0);p>=f.day&&d.setUTCHours(0);p>=4*f.day&&d.setUTCDate(1);p>=f.year&&d.setUTCMonth(0);var g=0,m=Number.NaN,j;do if(j=m,m=d.getTime(),b.push({v:m,label:a.tickFormatter(m,
a)}),"month"==e)if(1>c){d.setUTCDate(1);var h=d.getTime();d.setUTCMonth(d.getUTCMonth()+1);var wa=d.getTime();d.setTime(m+g*f.hour+(wa-h)*c);g=d.getUTCHours();d.setUTCHours(0)}else d.setUTCMonth(d.getUTCMonth()+c);else"year"==e?d.setUTCFullYear(d.getUTCFullYear()+c):d.setTime(m+p);while(m<a.max&&m!=j);return b};p=function(a,b){var c=new Date(a);if(null!=d.timeformat)return v.plot.formatDate(c,d.timeformat,d.monthNames);var e=b.tickSize[0]*f[b.tickSize[1]],p=b.max-b.min;fmt=e<f.minute?"%h:%M:%S":e<
f.day?p<2*f.day?"%h:%M":"%b %d %h:%M":e<f.month?"%b %d":e<f.year?p<f.year?"%b":"%b %y":"%y";return v.plot.formatDate(c,fmt,d.monthNames)}}else{var j=d.tickDecimals,h=-Math.floor(Math.log(b)/Math.LN10);null!=j&&h>j&&(h=j);p=Math.pow(10,-h);b/=p;if(1.5>b)c=1;else if(3>b){if(c=2,2.25<b&&(null==j||h+1<=j))c=2.5,++h}else c=7.5>b?5:10;c*=p;null!=d.minTickSize&&c<d.minTickSize&&(c=d.minTickSize);null!=d.tickSize&&(c=d.tickSize);a.tickDecimals=Math.max(0,null!=j?j:h);b=function(a){var b=[],c=S(a.min,a.tickSize),
d=0,e=Number.NaN,p;do p=e,e=c+d*a.tickSize,b.push({v:e,label:a.tickFormatter(e,a)}),++d;while(e<a.max&&e!=p);return b};p=function(a,b){return a.toFixed(b.tickDecimals)}}a.tickSize=e?[c,e]:c;a.tickGenerator=b;a.tickFormatter=v.isFunction(d.tickFormatter)?function(a,b){return""+d.tickFormatter(a,b)}:p;null!=d.labelWidth&&(a.labelWidth=d.labelWidth);null!=d.labelHeight&&(a.labelHeight=d.labelHeight)}function xa(a,d){a.ticks=[];if(a.used){if(null==d.ticks)a.ticks=a.tickGenerator(a);else if("number"==
typeof d.ticks)0<d.ticks&&(a.ticks=a.tickGenerator(a));else if(d.ticks){var b=d.ticks;v.isFunction(b)&&(b=b({min:a.min,max:a.max}));var c,e;for(c=0;c<b.length;++c){var p=null,f=b[c];"object"==typeof f?(e=f[0],1<f.length&&(p=f[1])):e=f;null==p&&(p=a.tickFormatter(e,a));a.ticks[c]={v:e,label:p}}}null!=d.autoscaleMargin&&0<a.ticks.length&&(null==d.min&&(a.min=Math.min(a.min,a.ticks[0].v)),null==d.max&&1<a.ticks.length&&(a.max=Math.min(a.max,a.ticks[a.ticks.length-1].v)))}}function ya(){function a(a){null==
a.labelWidth&&(a.labelWidth=K/6);if(null==a.labelHeight){labels=[];for(i=0;i<a.ticks.length;++i)(l=a.ticks[i].label)&&labels.push('<div class="tickLabel" style="float:left;width:'+a.labelWidth+'px">'+l+"</div>");a.labelHeight=0;if(0<labels.length){var b=v('<div style="position:absolute;top:-10000px;width:10000px;font-size:smaller">'+labels.join("")+'<div style="clear:left"></div></div>').appendTo(C);a.labelHeight=b.height();b.remove()}}}function d(a){if(null==a.labelWidth||null==a.labelHeight){var b,
c=[],d;for(b=0;b<a.ticks.length;++b)(d=a.ticks[b].label)&&c.push('<div class="tickLabel">'+d+"</div>");0<c.length&&(b=v('<div style="position:absolute;top:-10000px;font-size:smaller">'+c.join("")+"</div>").appendTo(C),null==a.labelWidth&&(a.labelWidth=b.width()),null==a.labelHeight&&(a.labelHeight=b.find("div").height()),b.remove());null==a.labelWidth&&(a.labelWidth=0);null==a.labelHeight&&(a.labelHeight=0)}}a(g.xaxis);d(g.yaxis);a(g.x2axis);d(g.y2axis);var b=j.grid.borderWidth;for(i=0;i<B.length;++i)b=
Math.max(b,2*(B[i].points.radius+B[i].points.lineWidth/2));s.left=s.right=s.top=s.bottom=b;var c=j.grid.labelMargin+j.grid.borderWidth;0<g.xaxis.labelHeight&&(s.bottom=Math.max(b,g.xaxis.labelHeight+c));0<g.yaxis.labelWidth&&(s.left=Math.max(b,g.yaxis.labelWidth+c));0<g.x2axis.labelHeight&&(s.top=Math.max(b,g.x2axis.labelHeight+c));0<g.y2axis.labelWidth&&(s.right=Math.max(b,g.y2axis.labelWidth+c));z=K-s.left-s.right;y=L-s.bottom-s.top;g.xaxis.scale=z/(g.xaxis.max-g.xaxis.min);g.yaxis.scale=y/(g.yaxis.max-
g.yaxis.min);g.x2axis.scale=z/(g.x2axis.max-g.x2axis.min);g.y2axis.scale=y/(g.y2axis.max-g.y2axis.min)}function ga(){var a;f.save();f.clearRect(0,0,K,L);f.translate(s.left,s.top);j.grid.backgroundColor&&(f.fillStyle=ha(j.grid.backgroundColor,y,0,"rgba(255, 255, 255, 0)"),f.fillRect(0,0,z,y));var d=j.grid.markings;if(d){v.isFunction(d)&&(d=d({xmin:g.xaxis.min,xmax:g.xaxis.max,ymin:g.yaxis.min,ymax:g.yaxis.max,xaxis:g.xaxis,yaxis:g.yaxis,x2axis:g.x2axis,y2axis:g.y2axis}));for(a=0;a<d.length;++a){var b=
d[a],c=V(b,"x"),e=V(b,"y");null==c.from&&(c.from=c.axis.min);null==c.to&&(c.to=c.axis.max);null==e.from&&(e.from=e.axis.min);null==e.to&&(e.to=e.axis.max);c.to<c.axis.min||c.from>c.axis.max||e.to<e.axis.min||e.from>e.axis.max||(c.from=Math.max(c.from,c.axis.min),c.to=Math.min(c.to,c.axis.max),e.from=Math.max(e.from,e.axis.min),e.to=Math.min(e.to,e.axis.max),c.from==c.to&&e.from==e.to||(c.from=c.axis.p2c(c.from),c.to=c.axis.p2c(c.to),e.from=e.axis.p2c(e.from),e.to=e.axis.p2c(e.to),c.from==c.to||e.from==
e.to?(f.strokeStyle=b.color||j.grid.markingsColor,f.beginPath(),f.lineWidth=b.lineWidth||j.grid.markingsLineWidth,f.moveTo(c.from,e.from),f.lineTo(c.to,e.to),f.stroke()):(f.fillStyle=b.color||j.grid.markingsColor,f.fillRect(c.from,e.to,c.to-c.from,e.from-e.to))))}}f.lineWidth=1;f.strokeStyle=j.grid.tickColor;f.beginPath();b=g.xaxis;for(a=0;a<b.ticks.length;++a)d=b.ticks[a].v,d<=b.min||d>=g.xaxis.max||(f.moveTo(Math.floor(b.p2c(d))+f.lineWidth/2,0),f.lineTo(Math.floor(b.p2c(d))+f.lineWidth/2,y));b=
g.yaxis;for(a=0;a<b.ticks.length;++a)d=b.ticks[a].v,d<=b.min||d>=b.max||(f.moveTo(0,Math.floor(b.p2c(d))+f.lineWidth/2),f.lineTo(z,Math.floor(b.p2c(d))+f.lineWidth/2));b=g.x2axis;for(a=0;a<b.ticks.length;++a)d=b.ticks[a].v,d<=b.min||d>=b.max||(f.moveTo(Math.floor(b.p2c(d))+f.lineWidth/2,-5),f.lineTo(Math.floor(b.p2c(d))+f.lineWidth/2,5));b=g.y2axis;for(a=0;a<b.ticks.length;++a)d=b.ticks[a].v,d<=b.min||d>=b.max||(f.moveTo(z-5,Math.floor(b.p2c(d))+f.lineWidth/2),f.lineTo(z+5,Math.floor(b.p2c(d))+f.lineWidth/
2));f.stroke();j.grid.borderWidth&&(a=j.grid.borderWidth,f.lineWidth=a,f.strokeStyle=j.grid.borderColor,f.strokeRect(-a/2,-a/2,z+a,y+a));f.restore();for(a=0;a<B.length;++a)if(d=B[a],d.subseries)for(b=0;b<d.subseries.length;++b)ia(d.subseries[b]);else ia(d)}function V(a,d){var b=d+"axis",c=d+"2axis",e,p;a[b]?(e=g[b],p=a[b].from,b=a[b].to):a[c]?(e=g[c],p=a[c].from,b=a[c].to):(e=g[b],p=a[d+"1"],b=a[d+"2"]);return null!=p&&null!=b&&p>b?{from:b,to:p,axis:e}:{from:p,to:b,axis:e}}function za(){function a(a,
b){for(var p=0;p<a.ticks.length;++p){var f=a.ticks[p];f.label&&!(f.v<a.min||f.v>a.max)&&d.push(b(f,a))}}C.find(".tickLabels").remove();var d=['<div class="tickLabels" style="font-size:smaller;color:'+j.grid.color+'">'],b=j.grid.labelMargin+j.grid.borderWidth;a(g.xaxis,function(a,d){return'<div style="position:absolute;top:'+(s.top+y+b)+"px;left:"+Math.round(s.left+d.p2c(a.v)-d.labelWidth/2)+"px;width:"+d.labelWidth+'px;text-align:center" class="tickLabel">'+a.label+"</div>"});a(g.yaxis,function(a,
d){return'<div style="position:absolute;top:'+Math.round(s.top+d.p2c(a.v)-d.labelHeight/2)+"px;right:"+(s.right+z+b)+"px;width:"+d.labelWidth+'px;text-align:right" class="tickLabel">'+a.label+"</div>"});a(g.x2axis,function(a,d){return'<div style="position:absolute;bottom:'+(s.bottom+y+b)+"px;left:"+Math.round(s.left+d.p2c(a.v)-d.labelWidth/2)+"px;width:"+d.labelWidth+'px;text-align:center" class="tickLabel">'+a.label+"</div>"});a(g.y2axis,function(a,d){return'<div style="position:absolute;top:'+Math.round(s.top+
d.p2c(a.v)-d.labelHeight/2)+"px;left:"+(s.left+z+b)+"px;width:"+d.labelWidth+'px;text-align:left" class="tickLabel">'+a.label+"</div>"});d.push("</div>");C.append(d.join(""))}function ia(a){a.lines.show&&Ba(a);a.bars.show&&Ca(a);a.points.show&&Da(a)}function Ba(a){function d(a,b,d,c,e){var g=a.linespoints||a.points,a=a.incr,j=null,h=null;f.beginPath();for(var o=a;o<g.length;o+=a){var k=g[o-a],n=g[o-a+1],m=g[o],r=g[o+1];if(!(null==k||null==m)){if(n<=r&&n<e.min){if(r<e.min)continue;k=(e.min-n)/(r-n)*
(m-k)+k;n=e.min}else if(r<=n&&r<e.min){if(n<e.min)continue;m=(e.min-n)/(r-n)*(m-k)+k;r=e.min}if(n>=r&&n>e.max){if(r>e.max)continue;k=(e.max-n)/(r-n)*(m-k)+k;n=e.max}else if(r>=n&&r>e.max){if(n>e.max)continue;m=(e.max-n)/(r-n)*(m-k)+k;r=e.max}if(k<=m&&k<c.min){if(m<c.min)continue;n=(c.min-k)/(m-k)*(r-n)+n;k=c.min}else if(m<=k&&m<c.min){if(k<c.min)continue;r=(c.min-k)/(m-k)*(r-n)+n;m=c.min}if(k>=m&&k>c.max){if(m>c.max)continue;n=(c.max-k)/(m-k)*(r-n)+n;k=c.max}else if(m>=k&&m>c.max){if(k>c.max)continue;
r=(c.max-k)/(m-k)*(r-n)+n;m=c.max}(k!=j||n!=h)&&f.moveTo(c.p2c(k)+b,e.p2c(n)+d);j=m;h=r;f.lineTo(c.p2c(m)+b,e.p2c(r)+d)}}f.stroke()}function b(a,b,c){var d=a.linespoints||a.points,a=a.incr,e=Math.min(Math.max(0,c.min),c.max),g;g=0;for(var j=!1,h=a;h<d.length;h+=a){var o=d[h-a],k=d[h-a+1],n=d[h],m=d[h+1];if(j&&null!=o&&null==n)f.lineTo(b.p2c(g),c.p2c(e)),f.fill(),j=!1;else if(!(null==o||null==n)){if(o<=n&&o<b.min){if(n<b.min)continue;k=(b.min-o)/(n-o)*(m-k)+k;o=b.min}else if(n<=o&&n<b.min){if(o<b.min)continue;
m=(b.min-o)/(n-o)*(m-k)+k;n=b.min}if(o>=n&&o>b.max){if(n>b.max)continue;k=(b.max-o)/(n-o)*(m-k)+k;o=b.max}else if(n>=o&&n>b.max){if(o>b.max)continue;m=(b.max-o)/(n-o)*(m-k)+k;n=b.max}j||(f.beginPath(),f.moveTo(b.p2c(o),c.p2c(e)),j=!0);if(k>=c.max&&m>=c.max)f.lineTo(b.p2c(o),c.p2c(c.max)),f.lineTo(b.p2c(n),c.p2c(c.max)),g=n;else if(k<=c.min&&m<=c.min)f.lineTo(b.p2c(o),c.p2c(c.min)),f.lineTo(b.p2c(n),c.p2c(c.min)),g=n;else{var r=o,s=n;k<=m&&k<c.min&&m>=c.min?(o=(c.min-k)/(m-k)*(n-o)+o,k=c.min):m<=k&&
m<c.min&&k>=c.min&&(n=(c.min-k)/(m-k)*(n-o)+o,m=c.min);k>=m&&k>c.max&&m<=c.max?(o=(c.max-k)/(m-k)*(n-o)+o,k=c.max):m>=k&&m>c.max&&k<=c.max&&(n=(c.max-k)/(m-k)*(n-o)+o,m=c.max);o!=r&&(g=k<=c.min?c.min:c.max,f.lineTo(b.p2c(r),c.p2c(g)),f.lineTo(b.p2c(o),c.p2c(g)));f.lineTo(b.p2c(o),c.p2c(k));f.lineTo(b.p2c(n),c.p2c(m));n!=s&&(g=m<=c.min?c.min:c.max,f.lineTo(b.p2c(n),c.p2c(g)),f.lineTo(b.p2c(s),c.p2c(g)));g=Math.max(n,s)}}}j&&(f.lineTo(b.p2c(g),c.p2c(e)),f.fill())}f.save();f.translate(s.left,s.top);
f.lineJoin="round";var c=a.lines.lineWidth,e=a.shadowSize;0<c&&0<e&&(f.lineWidth=e,f.strokeStyle="rgba(0,0,0,0.1)",d(a.datapoints,1,Math.sqrt((c/2+e/2)*(c/2+e/2)-1),a.xaxis,a.yaxis),f.lineWidth=e/2,d(a.datapoints,1,Math.sqrt((c/2+e/4)*(c/2+e/4)-1),a.xaxis,a.yaxis));f.lineWidth=c;f.strokeStyle=a.color;if(e=$(a.lines,a.color,0,y))f.fillStyle=e,b(a.datapoints,a.xaxis,a.yaxis);0<c&&d(a.datapoints,0,0,a.xaxis,a.yaxis);f.restore()}function Da(a){function d(a,b,c,d,e,g,j){for(var h=a.points,a=a.incr,o=0;o<
h.length;o+=a){var k=h[o],n=h[o+1];null==k||k<g.min||k>g.max||n<j.min||n>j.max||(f.beginPath(),f.arc(g.p2c(k),j.p2c(n)+d,b,0,e,!0),c&&(f.fillStyle=c,f.fill()),f.stroke())}}f.save();f.translate(s.left,s.top);var b=a.lines.lineWidth,c=a.shadowSize,e=a.points.radius;0<b&&0<c&&(c/=2,f.lineWidth=c,f.strokeStyle="rgba(0,0,0,0.1)",d(a.datapoints,e,null,c+c/2,2*Math.PI,a.xaxis,a.yaxis),f.strokeStyle="rgba(0,0,0,0.2)",d(a.datapoints,e,null,c/2,2*Math.PI,a.xaxis,a.yaxis));f.lineWidth=b;f.strokeStyle=a.color;
d(a.datapoints,e,$(a.points,a.color),0,2*Math.PI,a.xaxis,a.yaxis);f.restore()}function ja(a,d,b,c,e,f,g,j,h,q,t){var s,u,o,k;t?(k=u=o=!0,s=!1,t=b,b=d+c,e=d+e,a<t&&(d=a,a=t,t=d,s=!0,u=!1)):(s=u=o=!0,k=!1,t=a+c,a+=e,e=b,b=d,b<e&&(d=b,b=e,e=d,k=!0,o=!1));if(!(a<j.min||t>j.max||b<h.min||e>h.max))if(t<j.min&&(t=j.min,s=!1),a>j.max&&(a=j.max,u=!1),e<h.min&&(e=h.min,k=!1),b>h.max&&(b=h.max,o=!1),t=j.p2c(t),e=h.p2c(e),a=j.p2c(a),b=h.p2c(b),g&&(q.beginPath(),q.moveTo(t,e),q.lineTo(t,b),q.lineTo(a,b),q.lineTo(a,
e),q.fillStyle=g(e,b),q.fill()),s||u||o||k)q.beginPath(),q.moveTo(t,e+f),s?q.lineTo(t,b+f):q.moveTo(t,b+f),o?q.lineTo(a,b+f):q.moveTo(a,b+f),u?q.lineTo(a,e+f):q.moveTo(a,e+f),k?q.lineTo(t,e+f):q.moveTo(t,e+f),q.stroke()}function Ca(a){f.save();f.translate(s.left,s.top);f.lineWidth=a.bars.lineWidth;f.strokeStyle=a.color;var d="left"==a.bars.align?0:-a.bars.barWidth/2;(function(b,c,d,g,j,h,s){for(var q=b.points,b=b.incr,t=0;t<q.length;t+=b)null!=q[t]&&ja(q[t],q[t+1],q[t+2],c,d,g,j,h,s,f,a.bars.horizontal)})(a.datapoints,
d,d+a.bars.barWidth,0,a.bars.fill?function(b,c){return $(a.bars,a.color,b,c)}:null,a.xaxis,a.yaxis);f.restore()}function $(a,d,b,c){var e=a.fill;if(!e)return null;if(a.fillColor)return ha(a.fillColor,b,c,d);a=F(d);a.a="number"==typeof e?e:0.4;a.normalize();return a.toString()}function Aa(){C.find(".legend").remove();if(j.legend.show){var a=[],d=!1,b=j.legend.labelFormatter,c,e;for(i=0;i<B.length;++i)if(c=B[i],e=c.label)0==i%j.legend.noColumns&&(d&&a.push("</tr>"),a.push("<tr>"),d=!0),b&&(e=b(e,c)),
a.push('<td class="legendColorBox"><div style="border:1px solid '+j.legend.labelBoxBorderColor+';padding:1px"><div style="width:4px;height:0;border:5px solid '+c.color+';overflow:hidden"></div></div></td><td class="legendLabel">'+e+"</td>");d&&a.push("</tr>");if(0!=a.length)if(d='<table style="font-size:smaller;color:'+j.grid.color+'">'+a.join("")+"</table>",null!=j.legend.container)v(j.legend.container).html(d);else if(a="",b=j.legend.position,c=j.legend.margin,null==c[0]&&(c=[c,c]),"n"==b.charAt(0)?
a+="top:"+(c[1]+s.top)+"px;":"s"==b.charAt(0)&&(a+="bottom:"+(c[1]+s.bottom)+"px;"),"e"==b.charAt(1)?a+="right:"+(c[0]+s.right)+"px;":"w"==b.charAt(1)&&(a+="left:"+(c[0]+s.left)+"px;"),d=v('<div class="legend">'+d.replace('style="','style="position:absolute;'+a+";")+"</div>").appendTo(C),0!=j.legend.backgroundOpacity){b=j.legend.backgroundColor;if(null==b){if(j.grid.backgroundColor&&"string"==typeof j.grid.backgroundColor)b=j.grid.backgroundColor;else{c=d;do{b=c.css("background-color").toLowerCase();
if(""!=b&&"transparent"!=b)break;c=c.parent()}while(!v.nodeName(c.get(0),"body"));b="rgba(0, 0, 0, 0)"==b?"transparent":b}b=F(b).adjust(null,null,null,1).toString()}c=d.children();v('<div style="position:absolute;width:'+c.width()+"px;height:"+c.height()+"px;"+a+"background-color:"+b+';"> </div>').prependTo(d).css("opacity",j.legend.backgroundOpacity)}}}function Ea(a){a=a||window.event;if(null==a.pageX&&null!=a.clientX){var d=document.documentElement,b=document.body;N.pageX=a.clientX+(d&&d.scrollLeft||
b.scrollLeft||0)-(d.clientLeft||0);N.pageY=a.clientY+(d&&d.scrollTop||b.scrollTop||0)-(d.clientTop||0)}else N.pageX=a.pageX,N.pageY=a.pageY;j.grid.hoverable&&ka("plothover",N,function(a){return!1!=a.hoverable});null!=j.crosshair.mode&&(D?E.x=-1:(la(E,N),O()));D&&(C.trigger("plotselecting",[W()?ma():null]),na(N))}function Fa(a){1==a.which&&(document.body.focus(),void 0!==document.onselectstart&&null==T&&(T=document.onselectstart,document.onselectstart=function(){return!1}),void 0!==document.ondrag&&
null==U&&(U=document.ondrag,document.ondrag=function(){return!1}),oa(u,a),N.pageX=null,D=!0,v(document).one("mouseup",Ga))}function Ha(){null!=j.crosshair.mode&&-1!=E.x&&(E.x=-1,O())}function Ia(a){aa?aa=!1:ka("plotclick",a,function(a){return!1!=a.clickable})}function ka(a,d,b){var c=Q.offset(),e={pageX:d.pageX,pageY:d.pageY},f=d.pageX-c.left-s.left,d=d.pageY-c.top-s.top;g.xaxis.used&&(e.x=g.xaxis.c2p(f));g.yaxis.used&&(e.y=g.yaxis.c2p(d));g.x2axis.used&&(e.x2=g.x2axis.c2p(f));g.y2axis.used&&(e.y2=
g.y2axis.c2p(d));var h=j.grid.mouseActiveRadius,u=h*h+1,x=null,q,t;for(q=0;q<B.length;++q)if(b(B[q])){var w=B[q],v=w.xaxis,o=w.yaxis,k=w.datapoints.points,n=w.datapoints.incr,m=v.c2p(f),r=o.c2p(d),A=h/v.scale,D=h/o.scale;if(w.lines.show||w.points.show)for(t=0;t<k.length;t+=n){var z=k[t],y=k[t+1];if(null!=z&&!(z-m>A||z-m<-A||y-r>D||y-r<-D))z=Math.abs(v.p2c(z)-f),y=Math.abs(o.p2c(y)-d),y=z*z+y*y,y<u&&(u=y,x=[q,t/n])}if(w.bars.show&&!x){v="left"==w.bars.align?0:-w.bars.barWidth/2;w=v+w.bars.barWidth;
for(t=0;t<k.length;t+=n)if(z=k[t],y=k[t+1],o=k[t+2],null!=z&&(B[q].bars.horizontal?m<=Math.max(o,z)&&m>=Math.min(o,z)&&r>=y+v&&r<=y+w:m>=z+v&&m<=z+w&&r>=Math.min(o,y)&&r<=Math.max(o,y)))x=[q,t/n]}}x?(q=x[0],t=x[1],b={datapoint:B[q].data[t],dataIndex:t,series:B[q],seriesIndex:q}):b=null;b&&(b.pageX=parseInt(b.series.xaxis.p2c(b.datapoint[0])+c.left+s.left),b.pageY=parseInt(b.series.yaxis.p2c(b.datapoint[1])+c.top+s.top));if(j.grid.autoHighlight){for(c=0;c<M.length;++c)f=M[c],f.auto==a&&(!b||!(f.series==
b.series&&f.point==b.datapoint))&&pa(f.series,f.point);b&&qa(b.series,b.datapoint,a)}C.trigger(a,[e,b])}function O(){ba||(ba=setTimeout(Ja,30))}function Ja(){ba=null;A.save();A.clearRect(0,0,K,L);A.translate(s.left,s.top);var a,d;for(a=0;a<M.length;++a)if(d=M[a],d.series.bars.show)Ka(d.series,d.point);else{var b=d.series,c=d.point;d=c[0];var c=c[1],e=b.xaxis,g=b.yaxis;if(!(d<e.min||d>e.max||c<g.min||c>g.max)){var h=b.points.radius+b.points.lineWidth/2;A.lineWidth=h;A.strokeStyle=F(b.color).scale(1,
1,1,0.5).toString();b=1.5*h;A.beginPath();A.arc(e.p2c(d),g.p2c(c),b,0,2*Math.PI,!0);A.stroke()}}R&&W()&&(A.strokeStyle=F(j.selection.color).scale(null,null,null,0.8).toString(),A.lineWidth=1,f.lineJoin="round",A.fillStyle=F(j.selection.color).scale(null,null,null,0.4).toString(),a=Math.min(u.x,x.x),b=Math.min(u.y,x.y),d=Math.abs(x.x-u.x),c=Math.abs(x.y-u.y),A.fillRect(a,b,d,c),A.strokeRect(a,b,d,c));a=E;b=j.crosshair.mode;null!=b&&-1!=a.x&&(A.strokeStyle=F(j.crosshair.color).scale(null,null,null,
0.8).toString(),A.lineWidth=1,f.lineJoin="round",A.beginPath(),-1!=b.indexOf("x")&&(A.moveTo(a.x,0),A.lineTo(a.x,y)),-1!=b.indexOf("y")&&(A.moveTo(0,a.y),A.lineTo(z,a.y)),A.stroke());A.restore()}function qa(a,d,b){"number"==typeof a&&(a=B[a]);"number"==typeof d&&(d=a.data[d]);var c=ra(a,d);-1==c?(M.push({series:a,point:d,auto:b}),O()):b||(M[c].auto=!1)}function pa(a,d){"number"==typeof a&&(a=B[a]);"number"==typeof d&&(d=a.data[d]);var b=ra(a,d);-1!=b&&(M.splice(b,1),O())}function ra(a,d){for(var b=
0;b<M.length;++b){var c=M[b];if(c.series==a&&c.point[0]==d[0]&&c.point[1]==d[1])return b}return-1}function Ka(a,d){A.lineWidth=a.bars.lineWidth;A.strokeStyle=F(a.color).scale(1,1,1,0.5).toString();var b=F(a.color).scale(1,1,1,0.5).toString(),c="left"==a.bars.align?0:-a.bars.barWidth/2;ja(d[0],d[1],d[2]||0,c,c+a.bars.barWidth,0,function(){return b},a.xaxis,a.yaxis,A,a.bars.horizontal)}function la(a,d){var b=Q.offset();a.x=P(0,d.pageX-b.left-s.left,z);a.y=P(0,d.pageY-b.top-s.top,y)}function sa(a){null==
a?E.x=-1:(E.x=P(0,null!=a.x?g.xaxis.p2c(a.x):g.x2axis.p2c(a.x2),z),E.y=P(0,null!=a.y?g.yaxis.p2c(a.y):g.y2axis.p2c(a.y2),y));O()}function ma(){var a=Math.min(u.x,x.x),d=Math.max(u.x,x.x),b=Math.max(u.y,x.y),c=Math.min(u.y,x.y),e={};g.xaxis.used&&(e.xaxis={from:g.xaxis.c2p(a),to:g.xaxis.c2p(d)});g.x2axis.used&&(e.x2axis={from:g.x2axis.c2p(a),to:g.x2axis.c2p(d)});g.yaxis.used&&(e.yaxis={from:g.yaxis.c2p(b),to:g.yaxis.c2p(c)});g.y2axis.used&&(e.y2axis={from:g.y2axis.c2p(b),to:g.y2axis.c2p(c)});return e}
function ta(){var a=ma();C.trigger("plotselected",[a]);g.xaxis.used&&g.yaxis.used&&C.trigger("selected",[{x1:a.xaxis.from,y1:a.yaxis.from,x2:a.xaxis.to,y2:a.yaxis.to}])}function Ga(a){void 0!==document.onselectstart&&(document.onselectstart=T);void 0!==document.ondrag&&(document.ondrag=U);D=!1;na(a);W()?(ta(),aa=!0):(C.trigger("plotunselected",[]),C.trigger("plotselecting",[null]));return!1}function oa(a,d){la(a,d);"y"==j.selection.mode&&(a.x=a==u?0:z);"x"==j.selection.mode&&(a.y=a==u?0:y)}function na(a){null!=
a.pageX&&(oa(x,a),W()?(R=!0,O()):ua(!0))}function ua(a){R&&(R=!1,O(),a||C.trigger("plotunselected",[]))}function W(){return 5<=Math.abs(x.x-u.x)&&5<=Math.abs(x.y-u.y)}function ha(a,d,b,c){if("string"==typeof a)return a;for(var d=f.createLinearGradient(0,b,0,d),b=0,e=a.colors.length;b<e;++b){var g=a.colors[b];d.addColorStop(b/(e-1),"string"==typeof g?g:F(c).scale(g.brightness,g.brightness,g.brightness,g.opacity))}return d}var B=[],j={colors:["#edc240","#afd8f8","#cb4b4b","#4da74d","#9440ed"],legend:{show:!0,
noColumns:1,labelFormatter:null,labelBoxBorderColor:"#ccc",container:null,position:"ne",margin:5,backgroundColor:null,backgroundOpacity:0.85},xaxis:{mode:null,min:null,max:null,autoscaleMargin:null,ticks:null,tickFormatter:null,labelWidth:null,labelHeight:null,tickDecimals:null,tickSize:null,minTickSize:null,monthNames:null,timeformat:null},yaxis:{autoscaleMargin:0.02},x2axis:{autoscaleMargin:null},y2axis:{autoscaleMargin:0.02},points:{show:!1,radius:3,lineWidth:2,fill:!0,fillColor:"#ffffff"},lines:{lineWidth:2,
fill:!1,fillColor:null,steps:!1},bars:{show:!1,lineWidth:2,barWidth:1,fill:!0,fillColor:null,align:"left",horizontal:!1},threshold:null,grid:{color:"#545454",backgroundColor:null,tickColor:"#dddddd",labelMargin:5,borderWidth:2,borderColor:null,markings:null,markingsColor:"#f4f4f4",markingsLineWidth:2,clickable:!1,hoverable:!1,autoHighlight:!0,mouseActiveRadius:10},selection:{mode:null,color:"#e8cfac"},crosshair:{mode:null,color:"#aa0000"},shadowSize:3},X=null,ca=null,Q=null,f=null,A=null,C=v(w),g=
{xaxis:{},yaxis:{},x2axis:{},y2axis:{}},s={left:0,right:0,top:0,bottom:0},K=0,L=0,z=0,y=0;T=void 0;U=void 0;this.setData=ea;this.setupGrid=fa;this.draw=ga;this.clearSelection=ua;this.setSelection=function(a,d){var b;"y"==j.selection.mode?(u.x=0,x.x=z):(b=V(a,"x"),u.x=b.axis.p2c(b.from),x.x=b.axis.p2c(b.to));"x"==j.selection.mode?(u.y=0,x.y=y):(b=V(a,"y"),u.y=b.axis.p2c(b.from),x.y=b.axis.p2c(b.to));R=!0;O();d||ta()};this.getCanvas=function(){return X};this.getPlotOffset=function(){return s};this.getData=
function(){return B};this.getAxes=function(){return g};this.setCrosshair=sa;this.clearCrosshair=function(){sa(null)};this.highlight=qa;this.unhighlight=pa;v.extend(!0,j,va);null==j.grid.borderColor&&(j.grid.borderColor=j.grid.color);j.xaxis.noTicks&&null==j.xaxis.ticks&&(j.xaxis.ticks=j.xaxis.noTicks);j.yaxis.noTicks&&null==j.yaxis.ticks&&(j.yaxis.ticks=j.yaxis.noTicks);j.grid.coloredAreas&&(j.grid.markings=j.grid.coloredAreas);j.grid.coloredAreasColor&&(j.grid.markingsColor=j.grid.coloredAreasColor);
ea(h);(function(){function a(a,b){var c=document.createElement("canvas");c.width=a;c.height=b;v.browser.msie&&(c=window.G_vmlCanvasManager.initElement(c));return c}K=C.width();L=C.height();C.html("");"static"==C.css("position")&&C.css("position","relative");if(0>=K||0>=L)throw"Invalid dimensions for plot, width = "+K+", height = "+L;X=v(a(K,L)).appendTo(C).get(0);f=X.getContext("2d");ca=v(a(K,L)).css({position:"absolute",left:0,top:0}).appendTo(C).get(0);A=ca.getContext("2d");Q=v([ca,X]);if(null!=
j.selection.mode||null!=j.crosshair.mode||j.grid.hoverable)Q.each(function(){this.onmousemove=Ea}),null!=j.selection.mode&&Q.mousedown(Fa);null!=j.crosshair.mode&&Q.mouseout(Ha);j.grid.clickable&&Q.click(Ia)})();fa();ga();var N={pageX:null,pageY:null};u={x:-1,y:-1};x={x:-1,y:-1};R=!1;D=!1;E={x:-1,y:-1};var M=[],aa=!1,ba=null}function S(w,h){return h*Math.floor(w/h)}function P(w,h,v){return h<w?w:h>v?v:h}function J(w,h,v,E){for(var D=["r","g","b","a"],u=4;-1<--u;)this[D[u]]=arguments[u]||(3==u?1:0);
this.toString=function(){return 1<=this.a?"rgb("+[this.r,this.g,this.b].join()+")":"rgba("+[this.r,this.g,this.b,this.a].join()+")"};this.scale=function(h,w,v,E){for(u=4;-1<--u;)null!=arguments[u]&&(this[D[u]]*=arguments[u]);return this.normalize()};this.adjust=function(h,w,v,E){for(u=4;-1<--u;)null!=arguments[u]&&(this[D[u]]+=arguments[u]);return this.normalize()};this.clone=function(){return new J(this.r,this.b,this.g,this.a)};this.normalize=function(){this.r=P(0,parseInt(this.r),255);this.g=P(0,
parseInt(this.g),255);this.b=P(0,parseInt(this.b),255);this.a=P(0,this.a,1);return this};this.normalize()}function F(w){var h;if(h=/rgb\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*\)/.exec(w))return new J(parseInt(h[1],10),parseInt(h[2],10),parseInt(h[3],10));if(h=/rgba\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]+(?:\.[0-9]+)?)\s*\)/.exec(w))return new J(parseInt(h[1],10),parseInt(h[2],10),parseInt(h[3],10),parseFloat(h[4]));if(h=/rgb\(\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*\)/.exec(w))return new J(2.55*
parseFloat(h[1]),2.55*parseFloat(h[2]),2.55*parseFloat(h[3]));if(h=/rgba\(\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\s*\)/.exec(w))return new J(2.55*parseFloat(h[1]),2.55*parseFloat(h[2]),2.55*parseFloat(h[3]),parseFloat(h[4]));if(h=/#([a-fA-F0-9]{2})([a-fA-F0-9]{2})([a-fA-F0-9]{2})/.exec(w))return new J(parseInt(h[1],16),parseInt(h[2],16),parseInt(h[3],16));if(h=/#([a-fA-F0-9])([a-fA-F0-9])([a-fA-F0-9])/.exec(w))return new J(parseInt(h[1]+
h[1],16),parseInt(h[2]+h[2],16),parseInt(h[3]+h[3],16));w=v.trim(w).toLowerCase();if("transparent"==w)return new J(255,255,255,0);h=da[w];return new J(h[0],h[1],h[2])}v.plot=function(w,h,v){return new Y(w,h,v)};v.plot.formatDate=function(w,h,v){var E=function(h){h=""+h;return 1==h.length?"0"+h:h},D=[],u=!1;null==v&&(v="Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec".split(","));for(var F=0;F<h.length;++F){var x=h.charAt(F);if(u){switch(x){case "h":x=""+w.getUTCHours();break;case "H":x=E(w.getUTCHours());
break;case "M":x=E(w.getUTCMinutes());break;case "S":x=E(w.getUTCSeconds());break;case "d":x=""+w.getUTCDate();break;case "m":x=""+(w.getUTCMonth()+1);break;case "y":x=""+w.getUTCFullYear();break;case "b":x=""+v[w.getUTCMonth()]}D.push(x);u=!1}else"%"==x?u=!0:D.push(x)}return D.join("")};var da={aqua:[0,255,255],azure:[240,255,255],beige:[245,245,220],black:[0,0,0],blue:[0,0,255],brown:[165,42,42],cyan:[0,255,255],darkblue:[0,0,139],darkcyan:[0,139,139],darkgrey:[169,169,169],darkgreen:[0,100,0],
darkkhaki:[189,183,107],darkmagenta:[139,0,139],darkolivegreen:[85,107,47],darkorange:[255,140,0],darkorchid:[153,50,204],darkred:[139,0,0],darksalmon:[233,150,122],darkviolet:[148,0,211],fuchsia:[255,0,255],gold:[255,215,0],green:[0,128,0],indigo:[75,0,130],khaki:[240,230,140],lightblue:[173,216,230],lightcyan:[224,255,255],lightgreen:[144,238,144],lightgrey:[211,211,211],lightpink:[255,182,193],lightyellow:[255,255,224],lime:[0,255,0],magenta:[255,0,255],maroon:[128,0,0],navy:[0,0,128],olive:[128,
128,0],orange:[255,165,0],pink:[255,192,203],purple:[128,0,128],violet:[128,0,128],red:[255,0,0],silver:[192,192,192],white:[255,255,255],yellow:[255,255,0]}})(jQuery);
//@ sourceMappingURL=jquery.flot.js.map