(function(c){function l(){c.fn.ajaxSubmit.debug&&window.console&&window.console.log&&window.console.log("[jquery.form] "+Array.prototype.join.call(arguments,""))}c.fn.ajaxSubmit=function(a){function g(){function g(){if(!p++){m.detachEvent?m.detachEvent("onload",g):m.removeEventListener("load",g,!1);var a=!0;try{if(q)throw"timeout";var b,e;e=m.contentWindow?m.contentWindow.document:m.contentDocument?m.contentDocument:m.document;var h="xml"==d.dataType||e.XMLDocument||c.isXMLDoc(e);l("isXml="+h);if(!h&&
(null==e.body||""==e.body.innerHTML)){if(--s){p=0;setTimeout(g,100);return}l("Could not access iframe DOM after 50 tries.");return}j.responseText=e.body?e.body.innerHTML:null;j.responseXML=e.XMLDocument?e.XMLDocument:e;j.getResponseHeader=function(a){return{"content-type":d.dataType}[a]};if("json"==d.dataType||"script"==d.dataType){var i=e.getElementsByTagName("textarea")[0];if(i)j.responseText=i.value;else{var r=e.getElementsByTagName("pre")[0];r&&(j.responseText=r.innerHTML)}}else"xml"==d.dataType&&
!j.responseXML&&null!=j.responseText&&(j.responseXML=f(j.responseText));b=c.httpData(j,d.dataType)}catch(o){a=!1,c.handleError(d,j,"error",o)}a&&(d.success(b,"success"),n&&c.event.trigger("ajaxSuccess",[j,d]));n&&c.event.trigger("ajaxComplete",[j,d]);n&&!--c.active&&c.event.trigger("ajaxStop");d.complete&&d.complete(j,a?"success":"error");setTimeout(function(){k.remove();j.responseXML=null},100)}}function f(a,b){window.ActiveXObject?(b=new ActiveXObject("Microsoft.XMLDOM"),b.async="false",b.loadXML(a)):
b=(new DOMParser).parseFromString(a,"text/xml");return b&&b.documentElement&&"parsererror"!=b.documentElement.tagName?b:null}var b=h[0];if(c(":input[name=submit]",b).length)alert('Error: Form elements must not be named "submit".');else{var d=c.extend({},c.ajaxSettings,a),e=c.extend(!0,{},c.extend(!0,{},c.ajaxSettings),d),i="jqFormIO"+(new Date).getTime(),k=c('<iframe id="'+i+'" name="'+i+'" src="about:blank" />'),m=k[0];k.css({position:"absolute",top:"-1000px",left:"-1000px"});var j={aborted:0,responseText:null,
responseXML:null,status:0,statusText:"n/a",getAllResponseHeaders:function(){},getResponseHeader:function(){},setRequestHeader:function(){},abort:function(){this.aborted=1;k.attr("src","about:blank")}},n=d.global;n&&!c.active++&&c.event.trigger("ajaxStart");n&&c.event.trigger("ajaxSend",[j,d]);if(e.beforeSend&&!1===e.beforeSend(j,e))e.global&&c.active--;else if(!j.aborted){var p=0,q=0;if(e=b.clk){var o=e.name;o&&!e.disabled&&(a.extraData=a.extraData||{},a.extraData[o]=e.value,"image"==e.type&&(a.extraData[name+
".x"]=b.clk_x,a.extraData[name+".y"]=b.clk_y))}setTimeout(function(){var e=h.attr("target"),f=h.attr("action");b.setAttribute("target",i);"POST"!=b.getAttribute("method")&&b.setAttribute("method","POST");b.getAttribute("action")!=d.url&&b.setAttribute("action",d.url);a.skipEncodingOverride||h.attr({encoding:"multipart/form-data",enctype:"multipart/form-data"});d.timeout&&setTimeout(function(){q=!0;g()},d.timeout);var j=[];try{if(a.extraData)for(var l in a.extraData)j.push(c('<input type="hidden" name="'+
l+'" value="'+a.extraData[l]+'" />').appendTo(b)[0]);k.appendTo("body");m.attachEvent?m.attachEvent("onload",g):m.addEventListener("load",g,!1);b.submit()}finally{b.setAttribute("action",f),e?b.setAttribute("target",e):h.removeAttr("target"),c(j).remove()}},10);var s=50}}}if(!this.length)return l("ajaxSubmit: skipping submit process - no element selected"),this;"function"==typeof a&&(a={success:a});var b=c.trim(this.attr("action"));b&&(b=(b.match(/^([^#]+)/)||[])[1]);b=b||window.location.href||"";
a=c.extend({url:b,type:this.attr("method")||"GET"},a||{});b={};this.trigger("form-pre-serialize",[this,a,b]);if(b.veto)return l("ajaxSubmit: submit vetoed via form-pre-serialize trigger"),this;if(a.beforeSerialize&&!1===a.beforeSerialize(this,a))return l("ajaxSubmit: submit aborted via beforeSerialize callback"),this;var f=this.formToArray(a.semantic);if(a.data){a.extraData=a.data;for(var d in a.data)if(a.data[d]instanceof Array)for(var i in a.data[d])f.push({name:d,value:a.data[d][i]});else f.push({name:d,
value:a.data[d]})}if(a.beforeSubmit&&!1===a.beforeSubmit(f,this,a))return l("ajaxSubmit: submit aborted via beforeSubmit callback"),this;this.trigger("form-submit-validate",[f,this,a,b]);if(b.veto)return l("ajaxSubmit: submit vetoed via form-submit-validate trigger"),this;d=c.param(f);"GET"==a.type.toUpperCase()?(a.url+=(0<=a.url.indexOf("?")?"&":"?")+d,a.data=null):a.data=d;var h=this,e=[];a.resetForm&&e.push(function(){h.resetForm()});a.clearForm&&e.push(function(){h.clearForm()});if(!a.dataType&&
a.target){var k=a.success||function(){};e.push(function(b){c(a.target).html(b).each(k,arguments)})}else a.success&&e.push(a.success);a.success=function(b,c){for(var g=0,d=e.length;g<d;g++)e[g].apply(a,[b,c,h])};d=c("input:file",this).fieldValue();i=!1;for(b=0;b<d.length;b++)d[b]&&(i=!0);a.iframe||i?a.closeKeepAlive?c.get(a.closeKeepAlive,g):g():c.ajax(a);this.trigger("form-submit-notify",[this,a]);return this};c.fn.ajaxForm=function(a){return this.ajaxFormUnbind().bind("submit.form-plugin",function(){c(this).ajaxSubmit(a);
return!1}).bind("click.form-plugin",function(a){var b=c(a.target);if(b.is(":submit,input:image")){var f=this;f.clk=a.target;"image"==a.target.type&&(void 0!=a.offsetX?(f.clk_x=a.offsetX,f.clk_y=a.offsetY):"function"==typeof c.fn.offset?(b=b.offset(),f.clk_x=a.pageX-b.left,f.clk_y=a.pageY-b.top):(f.clk_x=a.pageX-a.target.offsetLeft,f.clk_y=a.pageY-a.target.offsetTop));setTimeout(function(){f.clk=f.clk_x=f.clk_y=null},10)}})};c.fn.ajaxFormUnbind=function(){return this.unbind("submit.form-plugin click.form-plugin")};
c.fn.formToArray=function(a){var g=[];if(0==this.length)return g;var b=this[0],f=a?b.getElementsByTagName("*"):b.elements;if(!f)return g;for(var d=0,i=f.length;d<i;d++){var h=f[d],e=h.name;if(e)if(a&&b.clk&&"image"==h.type)!h.disabled&&b.clk==h&&(g.push({name:e,value:c(h).val()}),g.push({name:e+".x",value:b.clk_x},{name:e+".y",value:b.clk_y}));else if((h=c.fieldValue(h,!0))&&h.constructor==Array)for(var k=0,l=h.length;k<l;k++)g.push({name:e,value:h[k]});else null!==h&&"undefined"!=typeof h&&g.push({name:e,
value:h})}if(!a&&b.clk&&(a=c(b.clk),f=a[0],(e=f.name)&&!f.disabled&&"image"==f.type))g.push({name:e,value:a.val()}),g.push({name:e+".x",value:b.clk_x},{name:e+".y",value:b.clk_y});return g};c.fn.formSerialize=function(a){return c.param(this.formToArray(a))};c.fn.fieldSerialize=function(a){var g=[];this.each(function(){var b=this.name;if(b){var f=c.fieldValue(this,a);if(f&&f.constructor==Array)for(var d=0,i=f.length;d<i;d++)g.push({name:b,value:f[d]});else null!==f&&"undefined"!=typeof f&&g.push({name:this.name,
value:f})}});return c.param(g)};c.fn.fieldValue=function(a){for(var g=[],b=0,f=this.length;b<f;b++){var d=c.fieldValue(this[b],a);null===d||"undefined"==typeof d||d.constructor==Array&&!d.length||(d.constructor==Array?c.merge(g,d):g.push(d))}return g};c.fieldValue=function(a,c){var b=a.name,f=a.type,d=a.tagName.toLowerCase();"undefined"==typeof c&&(c=!0);if(c&&(!b||a.disabled||"reset"==f||"button"==f||("checkbox"==f||"radio"==f)&&!a.checked||("submit"==f||"image"==f)&&a.form&&a.form.clk!=a||"select"==
d&&-1==a.selectedIndex))return null;if("select"==d){var i=a.selectedIndex;if(0>i)return null;for(var b=[],d=a.options,h=(f="select-one"==f)?i+1:d.length,i=f?i:0;i<h;i++){var e=d[i];if(e.selected){var k=e.value;k||(k=e.attributes&&e.attributes.value&&!e.attributes.value.specified?e.text:e.value);if(f)return k;b.push(k)}}return b}return a.value};c.fn.clearForm=function(){return this.each(function(){c("input,select,textarea",this).clearFields()})};c.fn.clearFields=c.fn.clearInputs=function(){return this.each(function(){var a=
this.type,c=this.tagName.toLowerCase();"text"==a||"password"==a||"textarea"==c?this.value="":"checkbox"==a||"radio"==a?this.checked=!1:"select"==c&&(this.selectedIndex=-1)})};c.fn.resetForm=function(){return this.each(function(){("function"==typeof this.reset||"object"==typeof this.reset&&!this.reset.nodeType)&&this.reset()})};c.fn.enable=function(a){void 0==a&&(a=!0);return this.each(function(){this.disabled=!a})};c.fn.selected=function(a){void 0==a&&(a=!0);return this.each(function(){var g=this.type;
"checkbox"==g||"radio"==g?this.checked=a:"option"==this.tagName.toLowerCase()&&(g=c(this).parent("select"),a&&g[0]&&"select-one"==g[0].type&&g.find("option").selected(!1),this.selected=a)})}})(jQuery);
//@ sourceMappingURL=jquery.form.js.map