(function(a,b,c,d){"$:nomunge";var e=a(d),g=function(a,c){a.element.trigger("waypoint.reached",c);if(a.options.triggerOnce)a.element[b]("destroy")},j=function(a,c){for(var b=c.waypoints.length-1;0<=b&&c.waypoints[b].element[0]!==a[0];)b-=1;return b},i=[],k=function(b){a.extend(this,{element:a(b),oldScroll:0,waypoints:[],didScroll:!1,didResize:!1,doScroll:a.proxy(function(){var b=this.element.scrollTop(),d=b>this.oldScroll,k=this,f=a.grep(this.waypoints,function(a){return d?a.offset>k.oldScroll&&a.offset<=
b:a.offset<=k.oldScroll&&a.offset>b}),h=f.length;if(!this.oldScroll||!b)a[c]("refresh");this.oldScroll=b;h&&(d||f.reverse(),a.each(f,function(a,b){if(b.options.continuous||a===h-1)g(b,[d?"down":"up"])}))},this)});a(b).scroll(a.proxy(function(){this.didScroll||(this.didScroll=!0,d.setTimeout(a.proxy(function(){this.doScroll();this.didScroll=!1},this),a[c].settings.scrollThrottle))},this)).resize(a.proxy(function(){this.didResize||(this.didResize=!0,d.setTimeout(a.proxy(function(){a[c]("refresh");this.didResize=
!1},this),a[c].settings.resizeThrottle))},this));e.load(a.proxy(function(){this.doScroll()},this))},h=function(b){var c=null;a.each(i,function(a,d){if(d.element[0]===b)return c=d,!1});return c},f={init:function(d,f){this.each(function(){var e=a.fn[b].defaults.context,g,q=a(this);f&&f.context&&(e=f.context);a.isWindow(e)||(e=q.closest(e)[0]);g=h(e);g||(g=new k(e),i.push(g));var o=j(q,g),r=a.extend({},0>o?a.fn[b].defaults:g.waypoints[o].options,f);r.offset="bottom-in-view"===r.offset?function(){return(a.isWindow(e)?
a[c]("viewportHeight"):a(e).height())-a(this).outerHeight()}:r.offset;0>o?g.waypoints.push({element:q,offset:null,options:r}):g.waypoints[o].options=r;d&&q.bind("waypoint.reached",d);f&&f.handler&&q.bind("waypoint.reached",f.handler)});a[c]("refresh");return this},remove:function(){return this.each(function(b,c){var d=a(c);a.each(i,function(a,b){var c=j(d,b);0<=c&&b.waypoints.splice(c,1)})})},destroy:function(){return this.unbind("waypoint.reached")[b]("remove")}},o={refresh:function(){a.each(i,function(b,
d){var f=a.isWindow(d.element[0]),k=f?0:d.element.offset().top,h=f?a[c]("viewportHeight"):d.element.height(),i=f?0:d.element.scrollTop();a.each(d.waypoints,function(a,b){if(b){var c=b.options.offset,f=b.offset;"function"===typeof b.options.offset?c=b.options.offset.apply(b.element):"string"===typeof b.options.offset&&(c=parseFloat(b.options.offset),c=b.options.offset.indexOf("%")?Math.ceil(h*(c/100)):c);b.offset=b.element.offset().top-k+i-c;b.options.onlyOnScroll||(null!==f&&d.oldScroll>f&&d.oldScroll<=
b.offset?g(b,["up"]):null!==f&&d.oldScroll<f&&d.oldScroll>=b.offset?g(b,["down"]):!f&&i>b.offset&&g(b,["down"]))}});d.waypoints.sort(function(a,b){return a.offset-b.offset})})},viewportHeight:function(){return d.innerHeight?d.innerHeight:e.height()},aggregate:function(){var b=a();a.each(i,function(c,d){a.each(d.waypoints,function(a,c){b=b.add(c.element)})});return b}};a.fn[b]=function(c){if(f[c])return f[c].apply(this,Array.prototype.slice.call(arguments,1));if("function"===typeof c||!c)return f.init.apply(this,
arguments);if("object"===typeof c)return f.init.apply(this,[null,c]);a.error("Method "+c+" does not exist on jQuery "+b)};a.fn[b].defaults={continuous:!0,offset:0,triggerOnce:!1,context:d};a[c]=function(a){return o[a]?o[a].apply(this):o.aggregate()};a[c].settings={resizeThrottle:200,scrollThrottle:100};e.load(function(){a[c]("refresh")})})(jQuery,"waypoint","waypoints",window);
$("html").ajaxSend(function(a,b,c){function d(a){var b=null;if(document.cookie&&""!=document.cookie)for(var c=document.cookie.split(";"),d=0;d<c.length;d++){var h=jQuery.trim(c[d]);if(h.substring(0,a.length+1)==a+"="){b=decodeURIComponent(h.substring(a.length+1));break}}return b}try{!/^http:.*/.test(c.url)&&!/^https:.*/.test(c.url)&&b.setRequestHeader("X-CSRFToken",d("csrftoken"))}catch(e){}});
var response_commands={refresh_page:function(){window.location.reload(!0)},update_post_score:function(a,b){var c=$("#post-"+a+"-score"),d=parseInt(c.html());isNaN(d)&&(d=0);c.html(d+b)},update_user_post_vote:function(a,b){var c=$("#post-"+a+"-upvote"),d=$("#post-"+a+"-downvote");c.removeClass("on");d.removeClass("on");"up"==b?c.addClass("on"):"down"==b&&d.addClass("on")},update_favorite_count:function(a){var b=$("#favorite-count"),c=parseInt(b.html());isNaN(c)&&(c=0);c+=a;0==c&&(c="");b.html(c)},
update_favorite_mark:function(a){"on"==a?$("#favorite-mark").addClass("on"):$("#favorite-mark").removeClass("on")},mark_accepted:function(a){a=$("#answer-container-"+a);a.addClass("accepted-answer");a.find(".accept-answer").addClass("on");a.find(".accept-answer").attr("title",a.find(".accept-answer").attr("bn:on"))},unmark_accepted:function(a){a=$("#answer-container-"+a);a.removeClass("accepted-answer");a.find(".accept-answer").removeClass("on");a.find(".accept-answer").attr("title",a.find(".accept-answer").attr("bn:off"))},
remove_comment:function(a){var b=$("#comment-"+a);b.css("background","red");b.fadeOut("slow",function(){b.remove()})},award_points:function(){alert("ok")},insert_comment:function(a,b,c,d,e,g,j,i,k,h){var f=$("#comments-container-"+a),a=$("#new-comment-skeleton-"+a).html().toString(),a=a.replace(RegExp("%ID%","g"),b).replace(RegExp("%COMMENT%","g"),c).replace(RegExp("%USERNAME%","g"),d).replace(RegExp("%PROFILE_URL%","g"),e).replace(RegExp("%DELETE_URL%","g"),g).replace(RegExp("%EDIT_URL%","g"),j).replace(RegExp("%CONVERT_URL%",
"g"),i);h?f.prepend(a):f.append(a);!0==k&&$("#comment-"+b+"-convert").show();$("#comment-"+b).slideDown("slow")},update_comment:function(a,b){var c=$("#comment-"+a);c.find(".comment-text").html(b);c.slideDown("slow")},mark_deleted:function(a,b){"question"==a?$("#question-table").addClass("deleted"):$("#"+a+"-container-"+b).addClass("deleted")},unmark_deleted:function(a,b){"answer"==a?$("#answer-container-"+b).removeClass("deleted"):$("#question-table").removeClass("deleted")},set_subscription_button:function(a){$(".subscription_switch").html(a)},
set_subscription_status:function(a){$(".subscription-status").html(a)},copy_url:function(){}};
function show_dialog(a){var b=function(a){a.fadeOut("fast",function(){a.remove()})},c={extra_class:"",pos:{x:$(window).width()/2+$(window).scrollLeft(),y:$(window).height()/2+$(window).scrollTop()},dim:!1,yes_text:messages.ok,yes_callback:b,no_text:messages.cancel,show_no:!1,close_on_clickoutside:!1,copy:!1};$.extend(c,a);a="";c.copy&&(a=' id="copy_clip_button"');void 0!=c.event&&(c.pos={x:c.event.pageX,y:c.event.pageY});var d='<div class="dialog '+c.extra_class+'" style="display: none;"><div class="dialog-content">'+
c.html+'</div><div class="dialog-buttons">';c.show_no&&(d+='<button class="dialog-no">'+c.no_text+"</button>");d+='<button class="dialog-yes"'+a+">"+c.yes_text+"</button></div></div>";$dialog=$(d);$("body").append($dialog);var e=$(".dialog-content")[0];e.style.visibility="hidden";!1===c.dim&&($dialog.css({visibility:"hidden",display:"block"}),c.dim={w:$dialog.width(),h:$dialog.height()},$dialog.css({width:1,height:1,visibility:"visible"}));$dialog.css({top:c.pos.y,left:c.pos.x});top_position_change=
c.dim.h/2;left_position_change=c.dim.w/2;new_top_position=c.pos.y-top_position_change;new_left_position=c.pos.x-left_position_change;0>new_left_position&&(left_position_change=0);0<$(window).scrollTop()-new_top_position&&(top_position_change=0);c.event.pageY+c.dim.h>$(window).height()+$(window).scrollTop()&&(top_position_change=c.dim.h);c.event.pageX+c.dim.w>$(window).width()+$(window).scrollLeft()&&(left_position_change=c.dim.w);$dialog.animate({top:"-="+top_position_change,left:"-="+left_position_change,
width:c.dim.w,height:c.dim.h},200,function(){e.style.visibility="visible"});$dialog.find(".dialog-no").click(function(){b($dialog)});$dialog.find(".dialog-yes").click(function(){c.yes_callback($dialog)});if(c.close_on_clickoutside)$dialog.one("clickoutside",function(){b($dialog)});return $dialog}function show_message(a,b,c){var d=show_dialog({html:b,extra_class:"warning",event:a,yes_callback:function(){d.fadeOut("fast",function(){d.remove()});c&&c()},close_on_clickoutside:!0})}
function load_prompt(a,b,c){$.get(c,function(d){d={html:d,extra_class:"prompt",yes_callback:function(){var b={};e.find("input, textarea, select").each(function(){b[$(this).attr("name")]=$(this).val()});$.post(c,b,function(b){e.fadeOut("fast",function(){e.remove()});process_ajax_response(b,a)},"json")},show_no:!0,copy:!1};b.hasClass("copy")&&$.extend(d,{yes_text:"Copy",copy:!0});b.is(".centered")||(d.event=a);var e=show_dialog(d)})}
function process_ajax_response(a,b,c){!a.success&&void 0!=a.error_message&&(show_message(b,a.error_message,function(){c&&c(!0)}),end_command(!1));if(void 0!=typeof a.commands){for(var d in a.commands)response_commands[d].apply(null,a.commands[d]);void 0!=a.message?show_message(b,a.message,function(){c&&c(false)}):c&&c(!1);end_command(!0)}}var running=!1;function start_command(){$("body").append($('<div id="command-loader"></div>'));running=!0}
function end_command(a){a?($("#command-loader").addClass("success"),$("#command-loader").fadeOut("slow",function(){$("#command-loader").remove();running=!1})):($("#command-loader").remove(),running=!1)}var comment_box_cursor_position=0;
function canned_comment(a,b){textarea=$("#comment-"+a+"-form textarea");textarea_start=textarea.val().substr(0,comment_box_cursor_position);textarea_end=textarea.val().substr(comment_box_cursor_position,textarea.val().length);textarea.val(textarea_start+b+textarea_end)}
function onready_function(){$("textarea.commentBox").bind("keydown keyup mousedown mouseup mousemove",function(){comment_box_cursor_position=$(this).caret().start});$("textarea.commentBox").blur(function(){});$("a.ajax-command").live("click",function(a){if(running)return!1;var b=$(this),c=b.attr("href"),c=c+"?nocache="+(new Date).getTime();$(".context-menu-dropdown").slideUp("fast");if(b.is(".withprompt"))load_prompt(a,b,c);else if(b.is(".confirm")){var d={html:messages.confirm,extra_class:"confirm",
yes_callback:function(){start_command();$.getJSON(c,function(b){process_ajax_response(b,a);e.fadeOut("fast",function(){e.remove()})})},yes_text:messages.yes,show_no:!0,no_text:messages.no};b.is(".centered")||(d.event=a);var e=show_dialog(d)}else start_command(),$.getJSON(c,function(b){process_ajax_response(b,a)});return!1});$(".context-menu").each(function(){var a=$(this),b=a.find(".context-menu-trigger"),c=a.find(".context-menu-dropdown");b.click(function(){c.slideToggle("fast",function(){if(c.is(":visible"))c.one("clickoutside",
function(){c.is(":visible")&&c.slideUp("fast")})})})});$("div.comment-form-container").each(function(){var a=$(this),b=a.parent().find(".comment-tools"),c=a.parent().find(".comments-container"),d=a.find("form");if(d.length){var e=a.find("textarea"),g=e.get(0),j=a.find(".comment-submit"),n=a.find(".comment-cancel"),l=a.find(".comments-chars-left-msg"),q=a.find(".comments-chars-togo-msg"),s=a.find(".comments-char-left-count"),r=b.find(".add-comment-link"),p=s.html().split("|"),u=parseInt(p[0]),y=parseInt(p[1]),
z=y-30,w=0,v=!1,x=null,D=!($.browser.msie||$.browser.opera);e.css("padding-top",0).css("padding-bottom",0).css("resize","none");g.style.overflow="hidden";var A=function(){e.val("");e.css("height",80);s.html(y);l.removeClass("warn");v=!1;w=0;l.hide();q.show();s.removeClass("warn");s.html(u);j.attr("disabled","disabled");x=null};A();var B=function(){a.slideDown("slow");r.fadeOut("slow");e.focus();x=window.setInterval(function(){var a=e.val().replace(/[ ]{2,}/g," ").length;if(w!=a){a<z&&w>=z?s.removeClass("warn"):
w<z&&a>=z&&s.addClass("warn");a<u?(l.hide(),q.show(),s.html(u-a)):(a=e.val().length,q.hide(),l.show(),s.html(y-a));a>y||a<u?j.attr("disabled","disabled"):j.removeAttr("disabled");var b=g.style.height;D&&(g.style.height="0px");var c=Math.max(80,g.scrollHeight);g.style.height=b;e.animate({height:c+"px"},50);w=a}},200)},C=function(){null!=x&&(window.clearInterval(x),x=null);a.slideUp("slow");r.fadeIn("slow")};r.click(function(){A();B();return!1});$("#"+c.attr("id")+" .comment-edit").live("click",function(){var a=
$(this),b=/comment-(\d+)-edit/.exec(a.attr("id"))[1],c=$("#comment-"+b);v=b;$.get(a.attr("href"),function(a){e.val(a)});c.slideUp("slow");B();return!1});j.click(function(a){if(running)return!1;var b={comment:e.val()};v&&(b.id=v);start_command();$.post(d.attr("action"),b,function(b){process_ajax_response(b,a,function(a){a||(A(),C())})},"json");return!1});e.keydown(function(a){a.ctrlKey&&13==a.keyCode&&!j.attr("disabled")&&$(this).parent().find("input.comment-submit").click()});n.click(function(){confirm("You will lose all of your changes in this comment.  Do you still wish to proceed?")&&
(v&&($comment=$("#comment-"+v).slideDown("slow")),C(),A());return!1})}b.find(".show-all-comments-link").click(function(){c.find(".not_top_scorer").slideDown("slow");$(this).fadeOut("slow");b.find(".comments-showing").fadeOut("slow");return!1})});if($("#editor").length){var a=$("#editor"),b=$("#previewer"),c=$("#editor-metrics"),d=/^[^A-Za-z\u0410-\u042f\u0430-\u044f0-9]+/gi,e=rExp=/[^A-Za-z\u0410-\u042f\u0430-\u044f0-9]+/gi,g=null;a.focus(function(){null==g&&(g=window.setInterval(function(){var a=
b.text(),k=a.length,a=(a+" ").replace(d,"").replace(e," ").split(" ").length-1,k=k+" "+(1==k?messages.character:messages.characters),k=k+(" / "+a+" "+(1==a?messages.word:messages.words));c.html(k)},200))})}$.waypoints.settings.scrollThrottle=30;var a=$("#roof"),j=$("#navBar");a.waypoint(function(a,b){j.toggleClass("sticky","down"===b);a.stopPropagation()})}
function pickedTags(){var a=function(a,b,c,d){var f=scriptUrl;"add"==c?(f+=$.i18n._("mark-tag/"),f="good"==b?f+$.i18n._("interesting/"):f+$.i18n._("ignored/")):f+=$.i18n._("unmark-tag/");a={type:"POST",url:f+a+"/",data:""};!1!==d&&(a.success=d);$.ajax(a)},b=function(b,c,d,e){var f=function(){b[c].remove();delete b[c]};e?a(c,d,"remove",f):f()},c=function(a,c,d,e,f){a.click(function(){b(c,d,e,f);return!1})},d=function(d,e){var g=$.trim($(d).prev().attr("value")),h=interestingTags,f=ignoredTags,o;if("bad"==
e)h=ignoredTags,f=interestingTags,o=$("div .tags.ignored");else{if("good"!=e)return;o=$("div .tags.interesting")}g in f&&b(f,g,e,!1);g in h||a(g,e,"add",function(){var a=$("<span></span>");a.addClass("deletable-tag");var b=$("<a></a>");b.attr("rel","tag");b.attr("href",scriptUrl+$.i18n._("tags/")+g+"/");b.html(g);var d=$("span.delete-icon");c(d,h,g,e,!0);a.append(b);a.append(d);o.append(a);h[g]=a})},e=function(){var a=/^interesting-tag-/,b=/^ignored-tag-/;interestingTags={};ignoredTags={};$(".deletable-tag").each(function(d,
e){var f=$(e).attr("id"),g;if(a.test(f))f=f.replace("interesting-tag-",""),g=interestingTags,reason="good";else if(b.test(f))f=f.replace("ignored-tag-",""),g=ignoredTags,reason="bad";else return;g[f]=$(e);c($(e).find("span.delete-icon"),g,f,reason,!0)})},g=function(){$("#hideIgnoredTagsCb").unbind("click").click(function(){$.ajax({type:"POST",dataType:"json",cache:!1,url:scriptUrl+$.i18n._("command/"),data:{command:"toggle-ignored-questions"}})})};return{init:function(){e();g();$("#interestingTagInput, #ignoredTagInput").autocomplete(messages.matching_tags_url,
{minChars:1,matchContains:!0,max:20,formatItem:function(a){return a[1]+" ("+a[2]+")"},formatResult:function(a){return a[1]}});$("#interestingTagAdd").click(function(){d(this,"good")});$("#ignoredTagAdd").click(function(){d(this,"bad")})}}}
Hilite={elementid:"content",exact:!0,max_nodes:1E3,onload:!0,style_name:"hilite",style_name_suffix:!0,debug_referrer:"",search_engines:[["local","q"],["cnprog\\.","q"],["google\\.","q"],["search\\.yahoo\\.","p"],["search\\.msn\\.","q"],["search\\.live\\.","query"],["search\\.aol\\.","userQuery"],["ask\\.com","q"],["altavista\\.","q"],["feedster\\.","q"],["search\\.lycos\\.","q"],["alltheweb\\.","q"],["technorati\\.com/search/([^\\?/]+)",1],["dogpile\\.com/info\\.dogpl/search/web/([^\\?/]+)",1,!0]],
decodeReferrer:function(a){for(var b=RegExp(""),c=0;c<Hilite.search_engines.length;c++){var d=Hilite.search_engines[c];b.compile("^http://(www\\.)?"+d[0],"i");var e=a.match(b);if(e){if(a=isNaN(d[1])?Hilite.decodeReferrerQS(a,d[1]):e[d[1]+1])return a=decodeURIComponent(a),2<d.length&&d[2]&&(a=decodeURIComponent(a)),a=a.replace(/\'|"/g,""),a=a.split(/[\s,\+\.]+/);break}}return null},decodeReferrerQS:function(a,b){var c=a.indexOf("?"),d;if(0<=c){var e=new String(a.substring(c+1));for(d=c=0;0<=c&&0<=
(d=e.indexOf("=",c));){var g;g=e.substring(c,d);c=e.indexOf("&",d)+1;if(g==b)return 0>=c?e.substring(d+1):e.substring(d+1,c-1);if(0>=c)break}}return null},hiliteElement:function(a,b){if(b&&0!=a.childNodes.length){for(var c=[],d=0;d<b.length;d++)b[d]=b[d].toLowerCase(),Hilite.exact?c.push("\\b"+b[d]+"\\b"):c.push(b[d]);for(var c=RegExp(c.join("|"),"i"),e={},d=0;d<b.length;d++)e[b[d]]=Hilite.style_name_suffix?Hilite.style_name+(d+1):Hilite.style_name;Hilite.walkElements(a.childNodes[0],1,function(a){var b=
c.exec(a.data);if(b){var d=b[0],b=a.splitText(b.index);b.splitText(d.length);var k=a.ownerDocument.createElement("SPAN");a.parentNode.replaceChild(k,b);k.className=e[d.toLowerCase()];k.appendChild(b);return k}return a})}},hilite:function(){var a=Hilite.debug_referrer?Hilite.debug_referrer:document.referrer,b=null;(a=Hilite.decodeReferrer(a))&&(Hilite.elementid&&(b=document.getElementById(Hilite.elementid))||(b=document.body))&&Hilite.hiliteElement(b,a)},walkElements:function(a,b,c){for(var d=/^(script|style|textarea)/i,
e=0;a&&0<b;){e++;if(e>=Hilite.max_nodes){setTimeout(function(){Hilite.walkElements(a,b,c)},50);break}if(1==a.nodeType){if(!d.test(a.tagName)&&0<a.childNodes.length){a=a.childNodes[0];b++;continue}}else 3==a.nodeType&&(a=c(a));if(a.nextSibling)a=a.nextSibling;else for(;0<b;)if(a=a.parentNode,b--,a.nextSibling){a=a.nextSibling;break}}}};
if(Hilite.onload)if(window.attachEvent)window.attachEvent("onload",Hilite.hilite);else if(window.addEventListener)window.addEventListener("load",Hilite.hilite,!1);else{var __onload=window.onload;window.onload=function(){Hilite.hilite();__onload()}}var mediaUrl=function(a){return scriptUrl+"m/"+osqaSkin+"/"+a};
(function(a){a.i18n={setDictionary:function(){},_:function(a,c){var d=a;i18n_dict&&i18n_dict[a]&&(d=i18n_dict[a]);return this.printf(d,c)},toEntity:function(a){for(var c="",d=0;d<a.length;d++)c=128<a.charCodeAt(d)?c+("&#"+a.charCodeAt(d)+";"):c+a.charAt(d);return c},stripStr:function(a){return a.replace(/^\s*/,"").replace(/\s*$/,"")},stripStrML:function(a){for(var a=a.split("\n"),c=0;c<a.length;c++)a[c]=stripStr(a[c]);return stripStr(a.join(" "))},printf:function(a,c){if(!c)return a;for(var d="",
e=a.split("%s"),g=0;g<c.length;g++)e[g].lastIndexOf("%")==e[g].length-1&&g!=c.length-1&&(e[g]+="s"+e.splice(g+1,1)[0]),d+=e[g]+c[g];return d+e[e.length-1]}}})(jQuery);
var i18nZh={"insufficient privilege":"??????????","cannot pick own answer as best":"??????????????","anonymous users cannot select favorite questions":"?????????????","please login":"??????","anonymous users cannot vote":"????????",">15 points requried to upvote":"??+15?????????",">100 points required to downvote":"??+100?????????","please see":"??","cannot vote for own posts":"??????????","daily vote cap exhausted":"????????????????","cannot revoke old vote":"??????????????","please confirm offensive":"??????????????????????",
"anonymous users cannot flag offensive posts":"???????????","cannot flag message as offensive twice":"???????","flag offensive cap exhausted":"?????????????5?\u0091??\u0092???","need >15 points to report spam":"??+15??????\u0091???\u0092?","confirm delete":"?????/????????","anonymous users cannot delete/undelete":"???????????????","post recovered":"?????????????","post deleted":"????????????","add comment":"????","community karma points":"????","to comment, need":"????","delete this comment":"?????",
"hide comments":"????","add a comment":"????",comments:"??","confirm delete comment":"?????????",characters:"??","can write":"???","click to close":"???????","loading...":"???...","tags cannot be empty":"???????","tablimits info":"??5????????????20????","content cannot be empty":"???????","content minchars":"????? {0} ???","please enter title":"??????","title minchars":"????? {0} ???","delete":"??",undelete:"??",bold:"??",italic:"??",link:"???",quote:"??","preformatted text":"??",image:"??","numbered list":"??????",
"bulleted list":"??????",heading:"??","horizontal bar":"???",undo:"??",redo:"??","enter image url":'<b>??????</b></p><p>???<br />http://www.example.com/image.jpg   "????"',"enter url":'<b>??Web??</b></p><p>???<br />http://www.cnprog.com/   "????"</p>"',"upload image":"?????????"},i18nEn={"need >15 points to report spam":"need >15 points to report spam ",">15 points requried to upvote":">15 points required to upvote ","tags cannot be empty":"please enter at least one tag","anonymous users cannot vote":"sorry, anonymous users cannot vote ",
"anonymous users cannot select favorite questions":"sorry, anonymous users cannot select favorite questions ","to comment, need":"(to comment other people's posts, karma ","please see":"please see ","community karma points":" or more is necessary) - ","upload image":"Upload image:","enter image url":'enter URL of the image, e.g. http://www.example.com/image.jpg "image title"',"enter url":'enter Web address, e.g. http://www.example.com "page title"',"daily vote cap exhausted":"sorry, you've used up todays vote cap",
"cannot pick own answer as best":"sorry, you cannot accept your own answer","cannot revoke old vote":"sorry, older votes cannot be revoked","please confirm offensive":"are you sure this post is offensive, contains spam, advertising, malicious remarks, etc.?","flag offensive cap exhausted":"sorry, you've used up todays cap of flagging offensive messages ","confirm delete":"are you sure you want to delete this?","anonymous users cannot delete/undelete":"sorry, anonymous users cannot delete or undelete posts",
"post recovered":"your post is now restored!","post deleted":"your post has been deleted","confirm delete comment":"do you really want to delete this comment?","can write":"have ","tablimits info":"up to 5 tags, no more than 20 characters each","content minchars":"please enter more than {0} characters","title minchars":"please enter at least {0} characters",characters:"characters left","cannot vote for own posts":"sorry, you cannot vote for your own posts","cannot flag message as offensive twice":"cannot flag message as offensive twice ",
">100 points required to downvote":">100 points required to downvote "},i18nEs={"insufficient privilege":"privilegio insuficiente","cannot pick own answer as best":"no puede escoger su propia respuesta como la mejor","anonymous users cannot select favorite questions":"usuarios anonimos no pueden seleccionar","please login":"por favor inicie sesi\u00f3n","anonymous users cannot vote":"usuarios an\u00f3nimos no pueden votar",">15 points requried to upvote":">15 puntos requeridos para votar positivamente",
">100 points required to downvote":">100 puntos requeridos para votar negativamente","please see":"por favor vea","cannot vote for own posts":"no se puede votar por sus propias publicaciones","daily vote cap exhausted":"cuota de votos diarios excedida","cannot revoke old vote":"no puede revocar un voto viejo","please confirm offensive":"por favor confirme ofensiva","anonymous users cannot flag offensive posts":"usuarios an\u00f3nimos no pueden marcar publicaciones como ofensivas","cannot flag message as offensive twice":"no puede marcar mensaje como ofensivo dos veces",
"flag offensive cap exhausted":"cuota para marcar ofensivas ha sido excedida","need >15 points to report spam":"necesita >15 puntos para reportar spam","confirm delete":"\u00bfEst\u00e1 seguro que desea borrar esto?","anonymous users cannot delete/undelete":"usuarios an\u00f3nimos no pueden borrar o recuperar publicaciones","post recovered":"publicaci\u00f3n recuperada","post deleted":"publicaci\u00f3n borrada?","add comment":"agregar comentario","community karma points":"reputaci\u00f3n comunitaria",
"to comment, need":"para comentar, necesita reputaci\u00f3n","delete this comment":"borrar este comentario","hide comments":"ocultar comentarios","add a comment":"agregar comentarios",comments:"comentarios","confirm delete comment":"\u00bfRealmente desea borrar este comentario?",characters:"caracteres faltantes","can write":"tiene ","click to close":"haga click para cerrar","loading...":"cargando...","tags cannot be empty":"las etiquetas no pueden estar vac\u00edas","tablimits info":"hasta 5 etiquetas de no mas de 20 caracteres cada una",
"content cannot be empty":"el contenido no puede estar vac\u00edo","content minchars":"por favor introduzca mas de {0} caracteres","please enter title":"por favor ingrese un t\u00edtulo","title minchars":"por favor introduzca al menos {0} caracteres","delete":"borrar",undelete:"recuperar",bold:"negrita",italic:"cursiva",link:"enlace",quote:"citar","preformatted text":"texto preformateado",image:"imagen","numbered list":"lista numerada","bulleted list":"lista no numerada",heading:"??","horizontal bar":"barra horizontal",
undo:"deshacer",redo:"rehacer","enter image url":'introduzca la URL de la imagen, por ejemplo?<br />http://www.example.com/image.jpg   "titulo de imagen"',"enter url":'introduzca direcciones web, ejemplo?<br />http://www.cnprog.com/   "titulo del enlace"</p>"',"upload image":"cargar imagen?","questions/":"preguntas/","vote/":"votar/"},i18n={en:i18nEn,zh_CN:i18nZh,es:i18nEs},i18n_dict=i18n[i18nLang];
(function(a){function b(b){e=a(b.data.el);e.blur();j=b.clientY+document.documentElement.scrollTop;g=e.height()-j;e.css("opacity",0.25);a(document).mousemove(c).mouseup(d);return!1}function c(a){var b=a.clientY+document.documentElement.scrollTop,c=g+b;j>=b&&(c-=5);j=b;c=Math.max(i,c);e.height(c+"px");c<i&&d(a);return!1}function d(){a(document).unbind("mousemove",c).unbind("mouseup",d);e.css("opacity",1);e.focus();g=e=null;j=0}var e,g,j=0,i=32;a.fn.TextAreaResizer=function(){return this.each(function(){e=
a(this).addClass("processed");g=null;a(this).wrap('<div class="resizable-textarea"><span></span></div>').parent().append(a('<div class="grippie"></div>').bind("mousedown",{el:this},b));var c=a("div.grippie",a(this).parent())[0];c.style.marginRight=c.offsetWidth-a(this)[0].offsetWidth+"px"})}})(jQuery);
(function(a){a.fn.extend({autocomplete:function(b,c){var d="string"==typeof b,c=a.extend({},a.Autocompleter.defaults,{url:d?b:null,data:d?null:b,delay:d?a.Autocompleter.defaults.delay:10,max:c&&!c.scroll?10:150},c);c.highlight=c.highlight||function(a){return a};c.formatMatch=c.formatMatch||c.formatItem;return this.each(function(){new a.Autocompleter(this,c)})},result:function(a){return this.bind("result",a)},search:function(a){return this.trigger("search",[a])},flushCache:function(){return this.trigger("flushCache")},
setOptions:function(a){return this.trigger("setOptions",[a])},unautocomplete:function(){return this.trigger("unautocomplete")}});a.Autocompleter=function(b,c){var d,e;function g(){var a=p.selected();if(!a)return!1;var b=a.result;n=b;if(c.multiple){var d=i(m.val());1<d.length&&(b=d.slice(0,d.length-1).join(c.multipleSeparator)+c.multipleSeparator+b);b+=c.multipleSeparator}m.val(b);h();m.trigger("result",[a.data,a.value]);return!0}function j(a,b){if(s==d)p.hide();else{var e=m.val();if(b||e!=n)n=e,e=
k(e),e.length>=c.minChars?(m.addClass(c.loadingClass),c.matchCase||(e=e.toLowerCase()),o(e,f,h)):(m.removeClass(c.loadingClass),p.hide())}}function i(b){if(!b)return[""];var b=b.split(c.multipleSeparator),d=[];a.each(b,function(b,c){a.trim(c)&&(d[b]=a.trim(c))});return d}function k(a){if(!c.multiple)return a;a=i(a);return a[a.length-1]}function h(){var d=p.visible();p.hide();clearTimeout(t);m.removeClass(c.loadingClass);c.mustMatch&&m.search(function(a){a||(c.multiple?(a=i(m.val()).slice(0,-1),m.val(a.join(c.multipleSeparator)+
(a.length?c.multipleSeparator:""))):m.val(""))});d&&a.Autocompleter.Selection(b,b.value.length,b.value.length)}function f(d,f){if(f&&f.length&&q){m.removeClass(c.loadingClass);p.display(f,d);var g=f[0].value;c.autoFill&&k(m.val()).toLowerCase()==d.toLowerCase()&&s!=e&&(m.val(m.val()+g.substring(k(n).length)),a.Autocompleter.Selection(b,n.length,n.length+g.length));p.show()}else h()}function o(d,e,f){c.matchCase||(d=d.toLowerCase());var g=l.load(d);if(g&&g.length)e(d,g);else if("string"==typeof c.url&&
0<c.url.length){var h={timestamp:+new Date};a.each(c.extraParams,function(a,b){h[a]="function"==typeof b?b():b});a.ajax({mode:"abort",port:"autocomplete"+b.name,dataType:c.dataType,url:c.url,data:a.extend({q:k(d),limit:c.max},h),success:function(b){var f;if(!(f=c.parse&&c.parse(b))){f=[];for(var b=b.split("\n"),g=0;g<b.length;g++){var h=a.trim(b[g]);h&&(h=h.split("|"),f[f.length]={data:h,value:h[0],result:c.formatResult&&c.formatResult(h,h[0])||h[0]})}}l.add(d,f);e(d,f)}})}else p.emptyList(),f(d)}
d=46;e=8;var m=a(b).attr("autocomplete","off").addClass(c.inputClass),t,n="",l=a.Autocompleter.Cache(c),q=0,s,r={mouseDownOnSelect:!1},p=a.Autocompleter.Select(c,b,g,r),u;a.browser.opera&&a(b.form).bind("submit.autocomplete",function(){if(u)return u=!1});m.bind((a.browser.opera?"keypress":"keydown")+".autocomplete",function(b){s=b.keyCode;switch(b.keyCode){case 38:b.preventDefault();p.visible()?p.prev():j(0,!0);break;case 40:b.preventDefault();p.visible()?p.next():j(0,!0);break;case 33:b.preventDefault();
p.visible()?p.pageUp():j(0,!0);break;case 34:b.preventDefault();p.visible()?p.pageDown():j(0,!0);break;case c.multiple&&","==a.trim(c.multipleSeparator)&&188:case 9:case 13:if(g())return b.preventDefault(),u=!0,!1;break;case 27:p.hide();break;default:clearTimeout(t),t=setTimeout(j,c.delay)}}).focus(function(){q++}).blur(function(){q=0;r.mouseDownOnSelect||(clearTimeout(t),t=setTimeout(h,200))}).click(function(){1<q++&&!p.visible()&&j(0,!0)}).bind("search",function(){function b(a,d){var e;if(d&&d.length)for(var f=
0;f<d.length;f++)if(d[f].result.toLowerCase()==a.toLowerCase()){e=d[f];break}"function"==typeof c?c(e):m.trigger("result",e&&[e.data,e.value])}var c=1<arguments.length?arguments[1]:null;a.each(i(m.val()),function(a,c){o(c,b,b)})}).bind("flushCache",function(){l.flush()}).bind("setOptions",function(b,d){a.extend(c,d);"data"in d&&l.populate()}).bind("unautocomplete",function(){p.unbind();m.unbind();a(b.form).unbind(".autocomplete")})};a.Autocompleter.defaults={inputClass:"ac_input",resultsClass:"ac_results",
loadingClass:"ac_loading",minChars:1,delay:400,matchCase:!1,matchSubset:!0,matchContains:!1,cacheLength:10,max:100,mustMatch:!1,extraParams:{},selectFirst:!0,formatItem:function(a){return a[0]},formatMatch:null,autoFill:!1,width:0,multiple:!1,multipleSeparator:", ",highlight:function(a,c){return a.replace(RegExp("(?![^&;]+;)(?!<[^<>]*)("+c.replace(/([\^\$\(\)\[\]\{\}\*\.\+\?\|\\])/gi,"\\$1")+")(?![^<>]*>)(?![^&;]+;)","gi"),"<strong>$1</strong>")},scroll:!0,scrollHeight:180};a.Autocompleter.Cache=
function(b){function c(a,c){b.matchCase||(a=a.toLowerCase());var d=a.indexOf(c);return-1==d?!1:0==d||b.matchContains}function d(a,c){i>b.cacheLength&&g();j[a]||i++;j[a]=c}function e(){if(!b.data)return!1;var c={},e=0;b.url||(b.cacheLength=1);c[""]=[];for(var f=0,g=b.data.length;f<g;f++){var j=b.data[f],j="string"==typeof j?[j]:j,i=b.formatMatch(j,f+1,b.data.length);if(!1!==i){var n=i.charAt(0).toLowerCase();c[n]||(c[n]=[]);j={value:i,data:j,result:b.formatResult&&b.formatResult(j)||i};c[n].push(j);
e++<b.max&&c[""].push(j)}}a.each(c,function(a,c){b.cacheLength++;d(a,c)})}function g(){j={};i=0}var j={},i=0;setTimeout(e,25);return{flush:g,add:d,populate:e,load:function(d){if(!b.cacheLength||!i)return null;if(!b.url&&b.matchContains){var e=[],f;for(f in j)if(0<f.length){var g=j[f];a.each(g,function(a,b){c(b.value,d)&&e.push(b)})}return e}if(j[d])return j[d];if(b.matchSubset)for(f=d.length-1;f>=b.minChars;f--)if(g=j[d.substr(0,f)])return e=[],a.each(g,function(a,b){c(b.value,d)&&(e[e.length]=b)}),
e;return null}}};a.Autocompleter.Select=function(b,c,d,e){var g;function j(){t&&(n=a("<div/>").hide().addClass(b.resultsClass).css("position","absolute").appendTo(document.body),l=a("<ul/>").appendTo(n).mouseover(function(b){i(b).nodeName&&"LI"==i(b).nodeName.toUpperCase()&&(f=a("li",l).removeClass(g).index(i(b)),a(i(b)).addClass(g))}).click(function(b){a(i(b)).addClass(g);d();c.focus();return!1}).mousedown(function(){e.mouseDownOnSelect=!0}).mouseup(function(){e.mouseDownOnSelect=!1}),0<b.width&&
n.css("width",b.width),t=!1)}function i(a){for(a=a.target;a&&"LI"!=a.tagName;)a=a.parentNode;return!a?[]:a}function k(a){h.slice(f,f+1).removeClass(g);f+=a;0>f?f=h.size()-1:f>=h.size()&&(f=0);a=h.slice(f,f+1).addClass(g);if(b.scroll){var c=0;h.slice(0,f).each(function(){c+=this.offsetHeight});c+a[0].offsetHeight-l.scrollTop()>l[0].clientHeight?l.scrollTop(c+a[0].offsetHeight-l.innerHeight()):c<l.scrollTop()&&l.scrollTop(c)}}g="ac_over";var h,f=-1,o,m="",t=!0,n,l;return{display:function(c,d){j();o=
c;m=d;l.empty();for(var e=b.max&&b.max<o.length?b.max:o.length,i=0;i<e;i++)if(o[i]){var k=b.formatItem(o[i].data,i+1,e,o[i].value,m);!1!==k&&(k=a("<li/>").html(b.highlight(k,m)).addClass(0==i%2?"ac_even":"ac_odd").appendTo(l)[0],a.data(k,"ac_data",o[i]))}h=l.find("li");b.selectFirst&&(h.slice(0,1).addClass(g),f=0);a.fn.bgiframe&&l.bgiframe()},next:function(){k(1)},prev:function(){k(-1)},pageUp:function(){0!=f&&0>f-8?k(-f):k(-8)},pageDown:function(){f!=h.size()-1&&f+8>h.size()?k(h.size()-1-f):k(8)},
hide:function(){n&&n.hide();h&&h.removeClass(g);f=-1},visible:function(){return n&&n.is(":visible")},current:function(){return this.visible()&&(h.filter("."+g)[0]||b.selectFirst&&h[0])},show:function(){var d=a(c).offset();n.css({width:"string"==typeof b.width||0<b.width?b.width:a(c).width(),top:d.top+c.offsetHeight,left:d.left}).show();if(b.scroll&&(l.scrollTop(0),l.css({maxHeight:b.scrollHeight,overflow:"auto"}),a.browser.msie&&"undefined"===typeof document.body.style.maxHeight)){var e=0;h.each(function(){e+=
this.offsetHeight});d=e>b.scrollHeight;l.css("height",d?b.scrollHeight:e);d||h.width(l.width()-parseInt(h.css("padding-left"))-parseInt(h.css("padding-right")))}},selected:function(){var b=h&&h.filter("."+g).removeClass(g);return b&&b.length&&a.data(b[0],"ac_data")},emptyList:function(){l&&l.empty()},unbind:function(){n&&n.remove()}}};a.Autocompleter.Selection=function(a,c,d){if(a.setSelectionRange)a.setSelectionRange(c,d);else if(a.createTextRange){var e=a.createTextRange();e.collapse(!0);e.moveStart("character",
c);e.moveEnd("character",d);e.select()}else a.selectionStart&&(a.selectionStart=c,a.selectionEnd=d);a.focus()}})(jQuery);var notify=function(){var a=!1;return{show:function(b){b&&($("body").css("margin-top","2.2em"),$(".notify span").html(b));$(".notify").fadeIn("slow");a=!0},close:function(){$(".notify").fadeOut("fast");$("body").css("margin-top","0");a=!1},isVisible:function(){return a}}}();
(function(a,b,c){function d(d,g){function j(b){a(i).each(function(){var c=a(this);this!==b.target&&!c.has(b.target).length&&c.triggerHandler(g,[b.target])})}var g=g||d+c,i=a(),k=d+"."+g+"-special-event";a.event.special[g]={setup:function(){i=i.add(this);1===i.length&&a(b).bind(k,j)},teardown:function(){i=i.not(this);0===i.length&&a(b).unbind(k)},add:function(a){var b=a.handler;a.handler=function(a,c){a.target=c;b.apply(this,arguments)}}}}a.map("click,dblclick,mousemove,mousedown,mouseup,mouseover,mouseout,change,select,submit,keydown,keypress,keyup".split(","),
function(a){d(a)});d("focusin","focus"+c);d("focusout","blur"+c);a.addOutsideEvent=d})(jQuery,document,"outside");$(document).ready(function(){pickedTags().init();$("input#bnewaccount").click(function(){$("#bnewaccount").disabled=!0})});
function yourWorkWillBeLost(a){if(browserTester("chrome")||browserTester("safari"))return"Are you sure you want to leave?  Your work will be lost.";a||(a=window.event);a.cancelBubble=!0;a.returnValue="If you leave, your work will be lost.";a.stopPropagation&&(a.stopPropagation(),a.preventDefault());return a}function browserTester(a){return-1<navigator.userAgent.toLowerCase().indexOf(a)}
window.addEventListener||(window.attachEvent?(window.addEventListener=function(a,b){window.attachEvent("on"+a,b)},window.removeEventListener=function(a,b){window.detachEvent("on"+a,b)}):(window.addEventListener=function(a,b){window["on"+a]=b},window.removeEventListener=function(a){window["on"+a]=null}));
//@ sourceMappingURL=js/osqa.main.js.map