$("html").ajaxSend(function(a,c,b){function d(a){var b=null;if(document.cookie&&""!=document.cookie)for(var c=document.cookie.split(";"),d=0;d<c.length;d++){var j=jQuery.trim(c[d]);if(j.substring(0,a.length+1)==a+"="){b=decodeURIComponent(j.substring(a.length+1));break}}return b}try{!/^http:.*/.test(b.url)&&!/^https:.*/.test(b.url)&&c.setRequestHeader("X-CSRFToken",d("csrftoken"))}catch(e){}});
var response_commands={refresh_page:function(){window.location.reload(!0)},update_post_score:function(a,c){var b=$("#post-"+a+"-score"),d=parseInt(b.html());isNaN(d)&&(d=0);b.html(d+c)},update_user_post_vote:function(a,c){var b=$("#post-"+a+"-upvote"),d=$("#post-"+a+"-downvote");b.removeClass("on");d.removeClass("on");"up"==c?b.addClass("on"):"down"==c&&d.addClass("on")},update_favorite_count:function(a){var c=$("#favorite-count"),b=parseInt(c.html());isNaN(b)&&(b=0);b+=a;0==b&&(b="");c.html(b)},
update_favorite_mark:function(a){"on"==a?$("#favorite-mark").addClass("on"):$("#favorite-mark").removeClass("on")},mark_accepted:function(a){a=$("#answer-container-"+a);a.addClass("accepted-answer");a.find(".accept-answer").addClass("on");a.find(".accept-answer").attr("title",a.find(".accept-answer").attr("bn:on"))},unmark_accepted:function(a){a=$("#answer-container-"+a);a.removeClass("accepted-answer");a.find(".accept-answer").removeClass("on");a.find(".accept-answer").attr("title",a.find(".accept-answer").attr("bn:off"))},
remove_comment:function(a){var c=$("#comment-"+a);c.css("background","red");c.fadeOut("slow",function(){c.remove()})},award_points:function(){alert("ok")},insert_comment:function(a,c,b,d,e,f,k,i,g,j){var h=$("#comments-container-"+a),a=$("#new-comment-skeleton-"+a).html().toString(),a=a.replace(RegExp("%ID%","g"),c).replace(RegExp("%COMMENT%","g"),b).replace(RegExp("%USERNAME%","g"),d).replace(RegExp("%PROFILE_URL%","g"),e).replace(RegExp("%DELETE_URL%","g"),f).replace(RegExp("%EDIT_URL%","g"),k).replace(RegExp("%CONVERT_URL%",
"g"),i);j?h.prepend(a):h.append(a);!0==g&&$("#comment-"+c+"-convert").show();$("#comment-"+c).slideDown("slow")},update_comment:function(a,c){var b=$("#comment-"+a);b.find(".comment-text").html(c);b.slideDown("slow")},mark_deleted:function(a,c){"question"==a?$("#question-table").addClass("deleted"):$("#"+a+"-container-"+c).addClass("deleted")},unmark_deleted:function(a,c){"answer"==a?$("#answer-container-"+c).removeClass("deleted"):$("#question-table").removeClass("deleted")},set_subscription_button:function(a){$(".subscription_switch").html(a)},
set_subscription_status:function(a){$(".subscription-status").html(a)},copy_url:function(){}};
function show_dialog(a){var c=function(a){a.fadeOut("fast",function(){a.remove()})},b={extra_class:"",pos:{x:$(window).width()/2+$(window).scrollLeft(),y:$(window).height()/2+$(window).scrollTop()},dim:!1,yes_text:messages.ok,yes_callback:c,no_text:messages.cancel,show_no:!1,close_on_clickoutside:!1,copy:!1};$.extend(b,a);a="";b.copy&&(a=' id="copy_clip_button"');void 0!=b.event&&(b.pos={x:b.event.pageX,y:b.event.pageY});var d='<div class="dialog '+b.extra_class+'" style="display: none;"><div class="dialog-content">'+
b.html+'</div><div class="dialog-buttons">';b.show_no&&(d+='<button class="dialog-no">'+b.no_text+"</button>");d+='<button class="dialog-yes"'+a+">"+b.yes_text+"</button></div></div>";$dialog=$(d);$("body").append($dialog);var e=$(".dialog-content")[0];e.style.visibility="hidden";!1===b.dim&&($dialog.css({visibility:"hidden",display:"block"}),b.dim={w:$dialog.width(),h:$dialog.height()},$dialog.css({width:1,height:1,visibility:"visible"}));$dialog.css({top:b.pos.y,left:b.pos.x});top_position_change=
b.dim.h/2;left_position_change=b.dim.w/2;new_top_position=b.pos.y-top_position_change;new_left_position=b.pos.x-left_position_change;0>new_left_position&&(left_position_change=0);0<$(window).scrollTop()-new_top_position&&(top_position_change=0);b.event.pageY+b.dim.h>$(window).height()+$(window).scrollTop()&&(top_position_change=b.dim.h);b.event.pageX+b.dim.w>$(window).width()+$(window).scrollLeft()&&(left_position_change=b.dim.w);$dialog.animate({top:"-="+top_position_change,left:"-="+left_position_change,
width:b.dim.w,height:b.dim.h},200,function(){e.style.visibility="visible"});$dialog.find(".dialog-no").click(function(){c($dialog)});$dialog.find(".dialog-yes").click(function(){b.yes_callback($dialog)});if(b.close_on_clickoutside)$dialog.one("clickoutside",function(){c($dialog)});return $dialog}function show_message(a,c,b){var d=show_dialog({html:c,extra_class:"warning",event:a,yes_callback:function(){d.fadeOut("fast",function(){d.remove()});b&&b()},close_on_clickoutside:!0})}
function load_prompt(a,c,b){$.get(b,function(d){d={html:d,extra_class:"prompt",yes_callback:function(){var c={};e.find("input, textarea, select").each(function(){c[$(this).attr("name")]=$(this).val()});$.post(b,c,function(b){e.fadeOut("fast",function(){e.remove()});process_ajax_response(b,a)},"json")},show_no:!0,copy:!1};c.hasClass("copy")&&$.extend(d,{yes_text:"Copy",copy:!0});c.is(".centered")||(d.event=a);var e=show_dialog(d)})}
function process_ajax_response(a,c,b){!a.success&&void 0!=a.error_message&&(show_message(c,a.error_message,function(){b&&b(!0)}),end_command(!1));if(void 0!=typeof a.commands){for(var d in a.commands)response_commands[d].apply(null,a.commands[d]);void 0!=a.message?show_message(c,a.message,function(){b&&b(!1)}):b&&b(!1);end_command(!0)}}var running=!1;function start_command(){$("body").append($('<div id="command-loader"></div>'));running=!0}
function end_command(a){a?($("#command-loader").addClass("success"),$("#command-loader").fadeOut("slow",function(){$("#command-loader").remove();running=!1})):($("#command-loader").remove(),running=!1)}var comment_box_cursor_position=0;
function canned_comment(a,c){textarea=$("#comment-"+a+"-form textarea");textarea_start=textarea.val().substr(0,comment_box_cursor_position);textarea_end=textarea.val().substr(comment_box_cursor_position,textarea.val().length);textarea.val(textarea_start+c+textarea_end)}
function onready_function(){$("textarea.commentBox").bind("keydown keyup mousedown mouseup mousemove",function(){comment_box_cursor_position=$(this).caret().start});$("textarea.commentBox").blur(function(){});$("a.ajax-command").live("click",function(a){if(running)return!1;var b=$(this),c=b.attr("href"),c=c+"?nocache="+(new Date).getTime();$(".context-menu-dropdown").slideUp("fast");if(b.is(".withprompt"))load_prompt(a,b,c);else if(b.is(".confirm")){var d={html:messages.confirm,extra_class:"confirm",
yes_callback:function(){start_command();$.getJSON(c,function(b){process_ajax_response(b,a);e.fadeOut("fast",function(){e.remove()})})},yes_text:messages.yes,show_no:!0,no_text:messages.no};b.is(".centered")||(d.event=a);var e=show_dialog(d)}else start_command(),$.getJSON(c,function(b){process_ajax_response(b,a)});return!1});$(".context-menu").each(function(){var a=$(this),b=a.find(".context-menu-trigger"),c=a.find(".context-menu-dropdown");b.click(function(){c.slideToggle("fast",function(){if(c.is(":visible"))c.one("clickoutside",
function(){c.is(":visible")&&c.slideUp("fast")})})})});$("div.comment-form-container").each(function(){var a=$(this),b=a.parent().find(".comment-tools"),c=a.parent().find(".comments-container"),d=a.find("form");if(d.length){var e=a.find("textarea"),k=e.get(0),f=a.find(".comment-submit"),n=a.find(".comment-cancel"),m=a.find(".comments-chars-left-msg"),s=a.find(".comments-chars-togo-msg"),q=a.find(".comments-char-left-count"),u=b.find(".add-comment-link"),o=q.html().split("|"),t=parseInt(o[0]),y=parseInt(o[1]),
z=y-30,w=0,v=!1,x=null,D=!($.browser.msie||$.browser.opera);e.css("padding-top",0).css("padding-bottom",0).css("resize","none");k.style.overflow="hidden";var A=function(){e.val("");e.css("height",80);q.html(y);m.removeClass("warn");v=!1;w=0;m.hide();s.show();q.removeClass("warn");q.html(t);f.attr("disabled","disabled");x=null};A();var B=function(){a.slideDown("slow");u.fadeOut("slow");e.focus();x=window.setInterval(function(){var a=e.val().replace(/[ ]{2,}/g," ").length;if(w!=a){a<z&&w>=z?q.removeClass("warn"):
w<z&&a>=z&&q.addClass("warn");a<t?(m.hide(),s.show(),q.html(t-a)):(a=e.val().length,s.hide(),m.show(),q.html(y-a));a>y||a<t?f.attr("disabled","disabled"):f.removeAttr("disabled");var b=k.style.height;D&&(k.style.height="0px");var c=Math.max(80,k.scrollHeight);k.style.height=b;e.animate({height:c+"px"},50);w=a}},200)},C=function(){null!=x&&(window.clearInterval(x),x=null);a.slideUp("slow");u.fadeIn("slow")};u.click(function(){A();B();return!1});$("#"+c.attr("id")+" .comment-edit").live("click",function(){var a=
$(this),b=/comment-(\d+)-edit/.exec(a.attr("id"))[1],c=$("#comment-"+b);v=b;$.get(a.attr("href"),function(a){e.val(a)});c.slideUp("slow");B();return!1});f.click(function(a){if(running)return!1;var b={comment:e.val()};v&&(b.id=v);start_command();$.post(d.attr("action"),b,function(b){process_ajax_response(b,a,function(a){a||(A(),C())})},"json");return!1});e.keydown(function(a){a.ctrlKey&&13==a.keyCode&&!f.attr("disabled")&&$(this).parent().find("input.comment-submit").click()});n.click(function(){confirm("You will lose all of your changes in this comment.  Do you still wish to proceed?")&&
(v&&($comment=$("#comment-"+v).slideDown("slow")),C(),A());return!1})}b.find(".show-all-comments-link").click(function(){c.find(".not_top_scorer").slideDown("slow");$(this).fadeOut("slow");b.find(".comments-showing").fadeOut("slow");return!1})});if($("#editor").length){var a=$("#editor"),c=$("#previewer"),b=$("#editor-metrics"),d=/^[^A-Za-z\u0410-\u042f\u0430-\u044f0-9]+/gi,e=rExp=/[^A-Za-z\u0410-\u042f\u0430-\u044f0-9]+/gi,f=null;a.focus(function(){null==f&&(f=window.setInterval(function(){var a=
c.text(),g=a.length,a=(a+" ").replace(d,"").replace(e," ").split(" ").length-1,g=g+" "+(1==g?messages.character:messages.characters),g=g+(" / "+a+" "+(1==a?messages.word:messages.words));b.html(g)},200))})}$.waypoints.settings.scrollThrottle=30;var a=$("#roof"),k=$("#navBar");a.waypoint(function(a,b){k.toggleClass("sticky","down"===b);a.stopPropagation()})}
function pickedTags(){var a=function(a,b,c,d){var e=scriptUrl;"add"==c?(e+=$.i18n._("mark-tag/"),e="good"==b?e+$.i18n._("interesting/"):e+$.i18n._("ignored/")):e+=$.i18n._("unmark-tag/");a={type:"POST",url:e+a+"/",data:""};!1!==d&&(a.success=d);$.ajax(a)},c=function(b,c,d,e){var h=function(){b[c].remove();delete b[c]};e?a(c,d,"remove",h):h()},b=function(a,b,d,e,h){a.click(function(){c(b,d,e,h);return!1})},d=function(d,e){var g=$.trim($(d).prev().attr("value")),j=interestingTags,h=ignoredTags,f;if("bad"==
e)j=ignoredTags,h=interestingTags,f=$("div .tags.ignored");else{if("good"!=e)return;f=$("div .tags.interesting")}g in h&&c(h,g,e,!1);g in j||a(g,e,"add",function(){var a=$("<span></span>");a.addClass("deletable-tag");var c=$("<a></a>");c.attr("rel","tag");c.attr("href",scriptUrl+$.i18n._("tags/")+g+"/");c.html(g);var d=$("span.delete-icon");b(d,j,g,e,!0);a.append(c);a.append(d);f.append(a);j[g]=a})},e=function(){var a=/^interesting-tag-/,c=/^ignored-tag-/;interestingTags={};ignoredTags={};$(".deletable-tag").each(function(d,
e){var h=$(e).attr("id"),f;if(a.test(h))h=h.replace("interesting-tag-",""),f=interestingTags,reason="good";else if(c.test(h))h=h.replace("ignored-tag-",""),f=ignoredTags,reason="bad";else return;f[h]=$(e);b($(e).find("span.delete-icon"),f,h,reason,!0)})},f=function(){$("#hideIgnoredTagsCb").unbind("click").click(function(){$.ajax({type:"POST",dataType:"json",cache:!1,url:scriptUrl+$.i18n._("command/"),data:{command:"toggle-ignored-questions"}})})};return{init:function(){e();f();$("#interestingTagInput, #ignoredTagInput").autocomplete(messages.matching_tags_url,
{minChars:1,matchContains:!0,max:20,formatItem:function(a){return a[1]+" ("+a[2]+")"},formatResult:function(a){return a[1]}});$("#interestingTagAdd").click(function(){d(this,"good")});$("#ignoredTagAdd").click(function(){d(this,"bad")})}}}
Hilite={elementid:"content",exact:!0,max_nodes:1E3,onload:!0,style_name:"hilite",style_name_suffix:!0,debug_referrer:"",search_engines:[["local","q"],["cnprog\\.","q"],["google\\.","q"],["search\\.yahoo\\.","p"],["search\\.msn\\.","q"],["search\\.live\\.","query"],["search\\.aol\\.","userQuery"],["ask\\.com","q"],["altavista\\.","q"],["feedster\\.","q"],["search\\.lycos\\.","q"],["alltheweb\\.","q"],["technorati\\.com/search/([^\\?/]+)",1],["dogpile\\.com/info\\.dogpl/search/web/([^\\?/]+)",1,!0]]};
Hilite.decodeReferrer=function(a){for(var c=RegExp(""),b=0;b<Hilite.search_engines.length;b++){var d=Hilite.search_engines[b];c.compile("^http://(www\\.)?"+d[0],"i");var e=a.match(c);if(e){if(a=isNaN(d[1])?Hilite.decodeReferrerQS(a,d[1]):e[d[1]+1])return a=decodeURIComponent(a),2<d.length&&d[2]&&(a=decodeURIComponent(a)),a=a.replace(/\'|"/g,""),a=a.split(/[\s,\+\.]+/);break}}return null};
Hilite.decodeReferrerQS=function(a,c){var b=a.indexOf("?"),d;if(0<=b){var e=new String(a.substring(b+1));for(d=b=0;0<=b&&0<=(d=e.indexOf("=",b));){var f;f=e.substring(b,d);b=e.indexOf("&",d)+1;if(f==c)return 0>=b?e.substring(d+1):e.substring(d+1,b-1);if(0>=b)break}}return null};
Hilite.hiliteElement=function(a,c){if(c&&0!=a.childNodes.length){for(var b=[],d=0;d<c.length;d++)c[d]=c[d].toLowerCase(),Hilite.exact?b.push("\\b"+c[d]+"\\b"):b.push(c[d]);for(var b=RegExp(b.join("|"),"i"),e={},d=0;d<c.length;d++)e[c[d]]=Hilite.style_name_suffix?Hilite.style_name+(d+1):Hilite.style_name;Hilite.walkElements(a.childNodes[0],1,function(a){var c=b.exec(a.data);if(c){var d=c[0],c=a.splitText(c.index);c.splitText(d.length);var g=a.ownerDocument.createElement("SPAN");a.parentNode.replaceChild(g,
c);g.className=e[d.toLowerCase()];g.appendChild(c);return g}return a})}};Hilite.hilite=function(){var a=Hilite.debug_referrer?Hilite.debug_referrer:document.referrer,c=null;(a=Hilite.decodeReferrer(a))&&(Hilite.elementid&&(c=document.getElementById(Hilite.elementid))||(c=document.body))&&Hilite.hiliteElement(c,a)};
Hilite.walkElements=function(a,c,b){for(var d=/^(script|style|textarea)/i,e=0;a&&0<c;){e++;if(e>=Hilite.max_nodes){setTimeout(function(){Hilite.walkElements(a,c,b)},50);break}if(1==a.nodeType){if(!d.test(a.tagName)&&0<a.childNodes.length){a=a.childNodes[0];c++;continue}}else 3==a.nodeType&&(a=b(a));if(a.nextSibling)a=a.nextSibling;else for(;0<c;)if(a=a.parentNode,c--,a.nextSibling){a=a.nextSibling;break}}};
if(Hilite.onload)if(window.attachEvent)window.attachEvent("onload",Hilite.hilite);else if(window.addEventListener)window.addEventListener("load",Hilite.hilite,!1);else{var __onload=window.onload;window.onload=function(){Hilite.hilite();__onload()}}var mediaUrl=function(a){return scriptUrl+"m/"+osqaSkin+"/"+a};
(function(a){a.i18n={setDictionary:function(){},_:function(a,b){var d=a;i18n_dict&&i18n_dict[a]&&(d=i18n_dict[a]);return this.printf(d,b)},toEntity:function(a){for(var b="",d=0;d<a.length;d++)b=128<a.charCodeAt(d)?b+("&#"+a.charCodeAt(d)+";"):b+a.charAt(d);return b},stripStr:function(a){return a.replace(/^\s*/,"").replace(/\s*$/,"")},stripStrML:function(a){for(var a=a.split("\n"),b=0;b<a.length;b++)a[b]=stripStr(a[b]);return stripStr(a.join(" "))},printf:function(a,b){if(!b)return a;for(var d="",
e=a.split("%s"),f=0;f<b.length;f++)e[f].lastIndexOf("%")==e[f].length-1&&f!=b.length-1&&(e[f]+="s"+e.splice(f+1,1)[0]),d+=e[f]+b[f];return d+e[e.length-1]}}})(jQuery);
var i18nZh={"insufficient privilege":"??????????","cannot pick own answer as best":"??????????????","anonymous users cannot select favorite questions":"?????????????","please login":"??????","anonymous users cannot vote":"????????",">15 points requried to upvote":"??+15?????????",">100 points required to downvote":"??+100?????????","please see":"??","cannot vote for own posts":"??????????","daily vote cap exhausted":"????????????????","cannot revoke old vote":"??????????????","please confirm offensive":"??????????????????????",
"anonymous users cannot flag offensive posts":"???????????","cannot flag message as offensive twice":"???????","flag offensive cap exhausted":"?????????????5?\u0091??\u0092???","need >15 points to report spam":"??+15??????\u0091???\u0092?","confirm delete":"?????/????????","anonymous users cannot delete/undelete":"???????????????","post recovered":"?????????????","post deleted":"????????????","add comment":"????","community karma points":"????","to comment, need":"????","delete this comment":"?????",
"hide comments":"????","add a comment":"????",comments:"??","confirm delete comment":"?????????",characters:"??","can write":"???","click to close":"???????","loading...":"???...","tags cannot be empty":"???????","tablimits info":"??5????????????20????","content cannot be empty":"???????","content minchars":"????? {0} ???","please enter title":"??????","title minchars":"????? {0} ???","delete":"??",undelete:"??",bold:"??",italic:"??",link:"???",quote:"??","preformatted text":"??",image:"??","numbered list":"??????",
"bulleted list":"??????",heading:"??","horizontal bar":"???",undo:"??",redo:"??","enter image url":'<b>??????</b></p><p>???<br />http://www.example.com/image.jpg   "????"',"enter url":'<b>??Web??</b></p><p>???<br />http://www.cnprog.com/   "????"</p>"',"upload image":"?????????"},i18nEn={"need >15 points to report spam":"need >15 points to report spam ",">15 points requried to upvote":">15 points required to upvote ","tags cannot be empty":"please enter at least one tag","anonymous users cannot vote":"sorry, anonymous users cannot vote ",
"anonymous users cannot select favorite questions":"sorry, anonymous users cannot select favorite questions ","to comment, need":"(to comment other people's posts, karma ","please see":"please see ","community karma points":" or more is necessary) - ","upload image":"Upload image:","enter image url":'enter URL of the image, e.g. http://www.example.com/image.jpg "image title"',"enter url":'enter Web address, e.g. http://www.example.com "page title"',"daily vote cap exhausted":"sorry, you've used up todays vote cap",
"cannot pick own answer as best":"sorry, you cannot accept your own answer","cannot revoke old vote":"sorry, older votes cannot be revoked","please confirm offensive":"are you sure this post is offensive, contains spam, advertising, malicious remarks, etc.?","flag offensive cap exhausted":"sorry, you've used up todays cap of flagging offensive messages ","confirm delete":"are you sure you want to delete this?","anonymous users cannot delete/undelete":"sorry, anonymous users cannot delete or undelete posts",
"post recovered":"your post is now restored!","post deleted":"your post has been deleted","confirm delete comment":"do you really want to delete this comment?","can write":"have ","tablimits info":"up to 5 tags, no more than 20 characters each","content minchars":"please enter more than {0} characters","title minchars":"please enter at least {0} characters",characters:"characters left","cannot vote for own posts":"sorry, you cannot vote for your own posts","cannot flag message as offensive twice":"cannot flag message as offensive twice ",
">100 points required to downvote":">100 points required to downvote "},i18nEs={"insufficient privilege":"privilegio insuficiente","cannot pick own answer as best":"no puede escoger su propia respuesta como la mejor","anonymous users cannot select favorite questions":"usuarios anonimos no pueden seleccionar","please login":"por favor inicie sesi\u00f3n","anonymous users cannot vote":"usuarios an\u00f3nimos no pueden votar",">15 points requried to upvote":">15 puntos requeridos para votar positivamente",
">100 points required to downvote":">100 puntos requeridos para votar negativamente","please see":"por favor vea","cannot vote for own posts":"no se puede votar por sus propias publicaciones","daily vote cap exhausted":"cuota de votos diarios excedida","cannot revoke old vote":"no puede revocar un voto viejo","please confirm offensive":"por favor confirme ofensiva","anonymous users cannot flag offensive posts":"usuarios an\u00f3nimos no pueden marcar publicaciones como ofensivas","cannot flag message as offensive twice":"no puede marcar mensaje como ofensivo dos veces",
"flag offensive cap exhausted":"cuota para marcar ofensivas ha sido excedida","need >15 points to report spam":"necesita >15 puntos para reportar spam","confirm delete":"\u00bfEst\u00e1 seguro que desea borrar esto?","anonymous users cannot delete/undelete":"usuarios an\u00f3nimos no pueden borrar o recuperar publicaciones","post recovered":"publicaci\u00f3n recuperada","post deleted":"publicaci\u00f3n borrada?","add comment":"agregar comentario","community karma points":"reputaci\u00f3n comunitaria",
"to comment, need":"para comentar, necesita reputaci\u00f3n","delete this comment":"borrar este comentario","hide comments":"ocultar comentarios","add a comment":"agregar comentarios",comments:"comentarios","confirm delete comment":"\u00bfRealmente desea borrar este comentario?",characters:"caracteres faltantes","can write":"tiene ","click to close":"haga click para cerrar","loading...":"cargando...","tags cannot be empty":"las etiquetas no pueden estar vac\u00edas","tablimits info":"hasta 5 etiquetas de no mas de 20 caracteres cada una",
"content cannot be empty":"el contenido no puede estar vac\u00edo","content minchars":"por favor introduzca mas de {0} caracteres","please enter title":"por favor ingrese un t\u00edtulo","title minchars":"por favor introduzca al menos {0} caracteres","delete":"borrar",undelete:"recuperar",bold:"negrita",italic:"cursiva",link:"enlace",quote:"citar","preformatted text":"texto preformateado",image:"imagen","numbered list":"lista numerada","bulleted list":"lista no numerada",heading:"??","horizontal bar":"barra horizontal",
undo:"deshacer",redo:"rehacer","enter image url":'introduzca la URL de la imagen, por ejemplo?<br />http://www.example.com/image.jpg   "titulo de imagen"',"enter url":'introduzca direcciones web, ejemplo?<br />http://www.cnprog.com/   "titulo del enlace"</p>"',"upload image":"cargar imagen?","questions/":"preguntas/","vote/":"votar/"},i18n={en:i18nEn,zh_CN:i18nZh,es:i18nEs},i18n_dict=i18n[i18nLang];
(function(a){function c(c){e=a(c.data.el);e.blur();k=c.clientY+document.documentElement.scrollTop;f=e.height()-k;e.css("opacity",0.25);a(document).mousemove(b).mouseup(d);return!1}function b(a){var b=a.clientY+document.documentElement.scrollTop,c=f+b;k>=b&&(c-=5);k=b;c=Math.max(i,c);e.height(c+"px");c<i&&d(a);return!1}function d(){a(document).unbind("mousemove",b).unbind("mouseup",d);e.css("opacity",1);e.focus();f=e=null;k=0}var e,f,k=0,i=32;a.fn.TextAreaResizer=function(){return this.each(function(){e=
a(this).addClass("processed");f=null;a(this).wrap('<div class="resizable-textarea"><span></span></div>').parent().append(a('<div class="grippie"></div>').bind("mousedown",{el:this},c));var b=a("div.grippie",a(this).parent())[0];b.style.marginRight=b.offsetWidth-a(this)[0].offsetWidth+"px"})}})(jQuery);
(function(a){a.fn.extend({autocomplete:function(c,b){var d="string"==typeof c,b=a.extend({},a.Autocompleter.defaults,{url:d?c:null,data:d?null:c,delay:d?a.Autocompleter.defaults.delay:10,max:b&&!b.scroll?10:150},b);b.highlight=b.highlight||function(a){return a};b.formatMatch=b.formatMatch||b.formatItem;return this.each(function(){new a.Autocompleter(this,b)})},result:function(a){return this.bind("result",a)},search:function(a){return this.trigger("search",[a])},flushCache:function(){return this.trigger("flushCache")},
setOptions:function(a){return this.trigger("setOptions",[a])},unautocomplete:function(){return this.trigger("unautocomplete")}});a.Autocompleter=function(c,b){var d,e;function f(){var a=o.selected();if(!a)return!1;var c=a.result;n=c;if(b.multiple){var d=i(l.val());1<d.length&&(c=d.slice(0,d.length-1).join(b.multipleSeparator)+b.multipleSeparator+c);c+=b.multipleSeparator}l.val(c);j();l.trigger("result",[a.data,a.value]);return!0}function k(a,c){if(q==d)o.hide();else{var e=l.val();if(c||e!=n)n=e,e=
g(e),e.length>=b.minChars?(l.addClass(b.loadingClass),b.matchCase||(e=e.toLowerCase()),p(e,h,j)):(l.removeClass(b.loadingClass),o.hide())}}function i(c){if(!c)return[""];var c=c.split(b.multipleSeparator),d=[];a.each(c,function(b,c){a.trim(c)&&(d[b]=a.trim(c))});return d}function g(a){if(!b.multiple)return a;a=i(a);return a[a.length-1]}function j(){var d=o.visible();o.hide();clearTimeout(r);l.removeClass(b.loadingClass);b.mustMatch&&l.search(function(a){a||(b.multiple?(a=i(l.val()).slice(0,-1),l.val(a.join(b.multipleSeparator)+
(a.length?b.multipleSeparator:""))):l.val(""))});d&&a.Autocompleter.Selection(c,c.value.length,c.value.length)}function h(d,f){if(f&&f.length&&s){l.removeClass(b.loadingClass);o.display(f,d);var h=f[0].value;b.autoFill&&g(l.val()).toLowerCase()==d.toLowerCase()&&q!=e&&(l.val(l.val()+h.substring(g(n).length)),a.Autocompleter.Selection(c,n.length,n.length+h.length));o.show()}else j()}function p(d,e,f){b.matchCase||(d=d.toLowerCase());var h=m.load(d);if(h&&h.length)e(d,h);else if("string"==typeof b.url&&
0<b.url.length){var j={timestamp:+new Date};a.each(b.extraParams,function(a,b){j[a]="function"==typeof b?b():b});a.ajax({mode:"abort",port:"autocomplete"+c.name,dataType:b.dataType,url:b.url,data:a.extend({q:g(d),limit:b.max},j),success:function(c){var f;if(!(f=b.parse&&b.parse(c))){f=[];for(var c=c.split("\n"),h=0;h<c.length;h++){var g=a.trim(c[h]);g&&(g=g.split("|"),f[f.length]={data:g,value:g[0],result:b.formatResult&&b.formatResult(g,g[0])||g[0]})}}m.add(d,f);e(d,f)}})}else o.emptyList(),f(d)}
d=46;e=8;var l=a(c).attr("autocomplete","off").addClass(b.inputClass),r,n="",m=a.Autocompleter.Cache(b),s=0,q,u={mouseDownOnSelect:!1},o=a.Autocompleter.Select(b,c,f,u),t;a.browser.opera&&a(c.form).bind("submit.autocomplete",function(){if(t)return t=!1});l.bind((a.browser.opera?"keypress":"keydown")+".autocomplete",function(c){q=c.keyCode;switch(c.keyCode){case 38:c.preventDefault();o.visible()?o.prev():k(0,!0);break;case 40:c.preventDefault();o.visible()?o.next():k(0,!0);break;case 33:c.preventDefault();
o.visible()?o.pageUp():k(0,!0);break;case 34:c.preventDefault();o.visible()?o.pageDown():k(0,!0);break;case b.multiple&&","==a.trim(b.multipleSeparator)&&188:case 9:case 13:if(f())return c.preventDefault(),t=!0,!1;break;case 27:o.hide();break;default:clearTimeout(r),r=setTimeout(k,b.delay)}}).focus(function(){s++}).blur(function(){s=0;u.mouseDownOnSelect||(clearTimeout(r),r=setTimeout(j,200))}).click(function(){1<s++&&!o.visible()&&k(0,!0)}).bind("search",function(){function c(a,d){var e;if(d&&d.length)for(var f=
0;f<d.length;f++)if(d[f].result.toLowerCase()==a.toLowerCase()){e=d[f];break}"function"==typeof b?b(e):l.trigger("result",e&&[e.data,e.value])}var b=1<arguments.length?arguments[1]:null;a.each(i(l.val()),function(a,b){p(b,c,c)})}).bind("flushCache",function(){m.flush()}).bind("setOptions",function(c,d){a.extend(b,d);"data"in d&&m.populate()}).bind("unautocomplete",function(){o.unbind();l.unbind();a(c.form).unbind(".autocomplete")})};a.Autocompleter.defaults={inputClass:"ac_input",resultsClass:"ac_results",
loadingClass:"ac_loading",minChars:1,delay:400,matchCase:!1,matchSubset:!0,matchContains:!1,cacheLength:10,max:100,mustMatch:!1,extraParams:{},selectFirst:!0,formatItem:function(a){return a[0]},formatMatch:null,autoFill:!1,width:0,multiple:!1,multipleSeparator:", ",highlight:function(a,b){return a.replace(RegExp("(?![^&;]+;)(?!<[^<>]*)("+b.replace(/([\^\$\(\)\[\]\{\}\*\.\+\?\|\\])/gi,"\\$1")+")(?![^<>]*>)(?![^&;]+;)","gi"),"<strong>$1</strong>")},scroll:!0,scrollHeight:180};a.Autocompleter.Cache=
function(c){function b(a,b){c.matchCase||(a=a.toLowerCase());var d=a.indexOf(b);return-1==d?!1:0==d||c.matchContains}function d(a,b){i>c.cacheLength&&f();k[a]||i++;k[a]=b}function e(){if(!c.data)return!1;var b={},e=0;c.url||(c.cacheLength=1);b[""]=[];for(var f=0,k=c.data.length;f<k;f++){var l=c.data[f],l="string"==typeof l?[l]:l,i=c.formatMatch(l,f+1,c.data.length);if(!1!==i){var n=i.charAt(0).toLowerCase();b[n]||(b[n]=[]);l={value:i,data:l,result:c.formatResult&&c.formatResult(l)||i};b[n].push(l);
e++<c.max&&b[""].push(l)}}a.each(b,function(a,b){c.cacheLength++;d(a,b)})}function f(){k={};i=0}var k={},i=0;setTimeout(e,25);return{flush:f,add:d,populate:e,load:function(d){if(!c.cacheLength||!i)return null;if(!c.url&&c.matchContains){var e=[],f;for(f in k)if(0<f.length){var p=k[f];a.each(p,function(a,c){b(c.value,d)&&e.push(c)})}return e}if(k[d])return k[d];if(c.matchSubset)for(f=d.length-1;f>=c.minChars;f--)if(p=k[d.substr(0,f)])return e=[],a.each(p,function(a,c){b(c.value,d)&&(e[e.length]=c)}),
e;return null}}};a.Autocompleter.Select=function(c,b,d,e){var f;function k(){r&&(n=a("<div/>").hide().addClass(c.resultsClass).css("position","absolute").appendTo(document.body),m=a("<ul/>").appendTo(n).mouseover(function(b){i(b).nodeName&&"LI"==i(b).nodeName.toUpperCase()&&(h=a("li",m).removeClass(f).index(i(b)),a(i(b)).addClass(f))}).click(function(c){a(i(c)).addClass(f);d();b.focus();return!1}).mousedown(function(){e.mouseDownOnSelect=!0}).mouseup(function(){e.mouseDownOnSelect=!1}),0<c.width&&
n.css("width",c.width),r=!1)}function i(a){for(a=a.target;a&&"LI"!=a.tagName;)a=a.parentNode;return!a?[]:a}function g(a){j.slice(h,h+1).removeClass(f);h+=a;0>h?h=j.size()-1:h>=j.size()&&(h=0);a=j.slice(h,h+1).addClass(f);if(c.scroll){var b=0;j.slice(0,h).each(function(){b+=this.offsetHeight});b+a[0].offsetHeight-m.scrollTop()>m[0].clientHeight?m.scrollTop(b+a[0].offsetHeight-m.innerHeight()):b<m.scrollTop()&&m.scrollTop(b)}}f="ac_over";var j,h=-1,p,l="",r=!0,n,m;return{display:function(b,d){k();p=
b;l=d;m.empty();for(var e=c.max&&c.max<p.length?c.max:p.length,g=0;g<e;g++)if(p[g]){var i=c.formatItem(p[g].data,g+1,e,p[g].value,l);!1!==i&&(i=a("<li/>").html(c.highlight(i,l)).addClass(0==g%2?"ac_even":"ac_odd").appendTo(m)[0],a.data(i,"ac_data",p[g]))}j=m.find("li");c.selectFirst&&(j.slice(0,1).addClass(f),h=0);a.fn.bgiframe&&m.bgiframe()},next:function(){g(1)},prev:function(){g(-1)},pageUp:function(){0!=h&&0>h-8?g(-h):g(-8)},pageDown:function(){h!=j.size()-1&&h+8>j.size()?g(j.size()-1-h):g(8)},
hide:function(){n&&n.hide();j&&j.removeClass(f);h=-1},visible:function(){return n&&n.is(":visible")},current:function(){return this.visible()&&(j.filter("."+f)[0]||c.selectFirst&&j[0])},show:function(){var d=a(b).offset();n.css({width:"string"==typeof c.width||0<c.width?c.width:a(b).width(),top:d.top+b.offsetHeight,left:d.left}).show();if(c.scroll&&(m.scrollTop(0),m.css({maxHeight:c.scrollHeight,overflow:"auto"}),a.browser.msie&&"undefined"===typeof document.body.style.maxHeight)){var e=0;j.each(function(){e+=
this.offsetHeight});d=e>c.scrollHeight;m.css("height",d?c.scrollHeight:e);d||j.width(m.width()-parseInt(j.css("padding-left"))-parseInt(j.css("padding-right")))}},selected:function(){var b=j&&j.filter("."+f).removeClass(f);return b&&b.length&&a.data(b[0],"ac_data")},emptyList:function(){m&&m.empty()},unbind:function(){n&&n.remove()}}};a.Autocompleter.Selection=function(a,b,d){if(a.setSelectionRange)a.setSelectionRange(b,d);else if(a.createTextRange){var e=a.createTextRange();e.collapse(!0);e.moveStart("character",
b);e.moveEnd("character",d);e.select()}else a.selectionStart&&(a.selectionStart=b,a.selectionEnd=d);a.focus()}})(jQuery);var notify=function(){var a=!1;return{show:function(c){c&&($("body").css("margin-top","2.2em"),$(".notify span").html(c));$(".notify").fadeIn("slow");a=!0},close:function(){$(".notify").fadeOut("fast");$("body").css("margin-top","0");a=!1},isVisible:function(){return a}}}();
(function(a,c,b){function d(d,f){function k(b){a(i).each(function(){var c=a(this);this!==b.target&&!c.has(b.target).length&&c.triggerHandler(f,[b.target])})}var f=f||d+b,i=a(),g=d+"."+f+"-special-event";a.event.special[f]={setup:function(){i=i.add(this);1===i.length&&a(c).bind(g,k)},teardown:function(){i=i.not(this);0===i.length&&a(c).unbind(g)},add:function(a){var b=a.handler;a.handler=function(a,c){a.target=c;b.apply(this,arguments)}}}}a.map("click,dblclick,mousemove,mousedown,mouseup,mouseover,mouseout,change,select,submit,keydown,keypress,keyup".split(","),
function(a){d(a)});d("focusin","focus"+b);d("focusout","blur"+b);a.addOutsideEvent=d})(jQuery,document,"outside");$(document).ready(function(){pickedTags().init();$("input#bnewaccount").click(function(){$("#bnewaccount").disabled=!0})});
function yourWorkWillBeLost(a){if(browserTester("chrome")||browserTester("safari"))return"Are you sure you want to leave?  Your work will be lost.";a||(a=window.event);a.cancelBubble=!0;a.returnValue="If you leave, your work will be lost.";a.stopPropagation&&(a.stopPropagation(),a.preventDefault());return a}function browserTester(a){return-1<navigator.userAgent.toLowerCase().indexOf(a)}
window.addEventListener||(window.attachEvent?(window.addEventListener=function(a,c){window.attachEvent("on"+a,c)},window.removeEventListener=function(a,c){window.detachEvent("on"+a,c)}):(window.addEventListener=function(a,c){window["on"+a]=c},window.removeEventListener=function(a){window["on"+a]=null}));
//@ sourceMappingURL=osqa.main.js.map