$(function(){$(".string_list_widget_button").live("click",function(){$but=$(this);$but.is(".add")?($new=$('<div style="display: none;"><input style="width: 600px;" type="text" name="'+$but.attr("name")+'" value="" /><button class="string_list_widget_button">-</button></div>'),$but.before($new),$new.slideDown("fast")):$but.parent().slideUp("fast",function(){$but.parent().remove()});return!1});$(".fieldtool").each(function(){var c=$(this),a=c.parent().parent().find("input, textarea"),b=a.attr("name");
c.is(".context")?c.click(function(){var a=$('<input type="text" value="'+b+'" />');c.replaceWith(a)}):c.is(".default")&&(1==a.length&&(a.is("[type=text]")||a.is("textarea"))?c.click(function(){$.post(b+"/",function(b){a.val(b)})}):c.attr("href",b+"/"))});$(".url_field").each(function(){function c(){var c=p+"/"+a.val();b.attr("href",c);b.html(c)}var a=$(this),b=a.parent().find(".url_field_anchor"),p=b.attr("href");a.keyup(c);c()});$("#test_email_settings a.test_button").click(function(){$("div.test_status").hide("slow");
$("div.ajax_indicator").show("fast");$.post($(this).attr("href"),function(c){$("div.ajax_indicator").hide("fast");$("div.test_status").html(c);$("div.test_status").show("slow")})})});
(function(c){c.fn.extend({autocomplete:function(a,b){var p="string"==typeof a,b=c.extend({},c.Autocompleter.defaults,{url:p?a:null,data:p?null:a,delay:p?c.Autocompleter.defaults.delay:10,max:b&&!b.scroll?10:150},b);b.highlight=b.highlight||function(a){return a};b.formatMatch=b.formatMatch||b.formatItem;return this.each(function(){new c.Autocompleter(this,b)})},result:function(a){return this.bind("result",a)},search:function(a){return this.trigger("search",[a])},flushCache:function(){return this.trigger("flushCache")},
setOptions:function(a){return this.trigger("setOptions",[a])},unautocomplete:function(){return this.trigger("unautocomplete")}});c.Autocompleter=function(a,b){var p,q;function m(){var a=i.selected();if(!a)return!1;var c=a.result;k=c;if(b.multiple){var e=o(g.val());1<e.length&&(c=e.slice(0,e.length-1).join(b.multipleSeparator)+b.multipleSeparator+c);c+=b.multipleSeparator}g.val(c);f();g.trigger("result",[a.data,a.value]);return!0}function n(a,c){if(s==p)i.hide();else{var e=g.val();if(c||e!=k)k=e,e=
h(e),e.length>=b.minChars?(g.addClass(b.loadingClass),b.matchCase||(e=e.toLowerCase()),r(e,d,f)):(g.removeClass(b.loadingClass),i.hide())}}function o(a){if(!a)return[""];var a=a.split(b.multipleSeparator),e=[];c.each(a,function(a,b){c.trim(b)&&(e[a]=c.trim(b))});return e}function h(a){if(!b.multiple)return a;a=o(a);return a[a.length-1]}function f(){var e=i.visible();i.hide();clearTimeout(l);g.removeClass(b.loadingClass);b.mustMatch&&g.search(function(a){a||(b.multiple?(a=o(g.val()).slice(0,-1),g.val(a.join(b.multipleSeparator)+
(a.length?b.multipleSeparator:""))):g.val(""))});e&&c.Autocompleter.Selection(a,a.value.length,a.value.length)}function d(d,j){if(j&&j.length&&e){g.removeClass(b.loadingClass);i.display(j,d);var l=j[0].value;b.autoFill&&h(g.val()).toLowerCase()==d.toLowerCase()&&s!=q&&(g.val(g.val()+l.substring(h(k).length)),c.Autocompleter.Selection(a,k.length,k.length+l.length));i.show()}else f()}function r(e,d,f){b.matchCase||(e=e.toLowerCase());var g=j.load(e);if(g&&g.length)d(e,g);else if("string"==typeof b.url&&
0<b.url.length){var l={timestamp:+new Date};c.each(b.extraParams,function(a,b){l[a]="function"==typeof b?b():b});c.ajax({mode:"abort",port:"autocomplete"+a.name,dataType:b.dataType,url:b.url,data:c.extend({q:h(e),limit:b.max},l),success:function(a){var g;if(!(g=b.parse&&b.parse(a))){g=[];for(var a=a.split("\n"),f=0;f<a.length;f++){var h=c.trim(a[f]);h&&(h=h.split("|"),g[g.length]={data:h,value:h[0],result:b.formatResult&&b.formatResult(h,h[0])||h[0]})}}j.add(e,g);d(e,g)}})}else i.emptyList(),f(e)}
p=46;q=8;var g=c(a).attr("autocomplete","off").addClass(b.inputClass),l,k="",j=c.Autocompleter.Cache(b),e=0,s,u={mouseDownOnSelect:!1},i=c.Autocompleter.Select(b,a,m,u),t;c.browser.opera&&c(a.form).bind("submit.autocomplete",function(){if(t)return t=!1});g.bind((c.browser.opera?"keypress":"keydown")+".autocomplete",function(a){s=a.keyCode;switch(a.keyCode){case 38:a.preventDefault();i.visible()?i.prev():n(0,!0);break;case 40:a.preventDefault();i.visible()?i.next():n(0,!0);break;case 33:a.preventDefault();
i.visible()?i.pageUp():n(0,!0);break;case 34:a.preventDefault();i.visible()?i.pageDown():n(0,!0);break;case b.multiple&&","==c.trim(b.multipleSeparator)&&188:case 9:case 13:if(m())return a.preventDefault(),t=!0,!1;break;case 27:i.hide();break;default:clearTimeout(l),l=setTimeout(n,b.delay)}}).focus(function(){e++}).blur(function(){e=0;u.mouseDownOnSelect||(clearTimeout(l),l=setTimeout(f,200))}).click(function(){1<e++&&!i.visible()&&n(0,!0)}).bind("search",function(){function a(c,e){var f;if(e&&e.length)for(var d=
0;d<e.length;d++)if(e[d].result.toLowerCase()==c.toLowerCase()){f=e[d];break}"function"==typeof b?b(f):g.trigger("result",f&&[f.data,f.value])}var b=1<arguments.length?arguments[1]:null;c.each(o(g.val()),function(b,e){r(e,a,a)})}).bind("flushCache",function(){j.flush()}).bind("setOptions",function(a,e){c.extend(b,e);"data"in e&&j.populate()}).bind("unautocomplete",function(){i.unbind();g.unbind();c(a.form).unbind(".autocomplete")})};c.Autocompleter.defaults={inputClass:"ac_input",resultsClass:"ac_results",
loadingClass:"ac_loading",minChars:1,delay:400,matchCase:!1,matchSubset:!0,matchContains:!1,cacheLength:10,max:100,mustMatch:!1,extraParams:{},selectFirst:!0,formatItem:function(a){return a[0]},formatMatch:null,autoFill:!1,width:0,multiple:!1,multipleSeparator:", ",highlight:function(a,b){return a.replace(RegExp("(?![^&;]+;)(?!<[^<>]*)("+b.replace(/([\^\$\(\)\[\]\{\}\*\.\+\?\|\\])/gi,"\\$1")+")(?![^<>]*>)(?![^&;]+;)","gi"),"<strong>$1</strong>")},scroll:!0,scrollHeight:180};c.Autocompleter.Cache=
function(a){function b(b,c){a.matchCase||(b=b.toLowerCase());var d=b.indexOf(c);return-1==d?!1:0==d||a.matchContains}function p(b,c){o>a.cacheLength&&m();n[b]||o++;n[b]=c}function q(){if(!a.data)return!1;var b={},f=0;a.url||(a.cacheLength=1);b[""]=[];for(var d=0,m=a.data.length;d<m;d++){var g=a.data[d],g="string"==typeof g?[g]:g,l=a.formatMatch(g,d+1,a.data.length);if(!1!==l){var k=l.charAt(0).toLowerCase();b[k]||(b[k]=[]);g={value:l,data:g,result:a.formatResult&&a.formatResult(g)||l};b[k].push(g);
f++<a.max&&b[""].push(g)}}c.each(b,function(b,e){a.cacheLength++;p(b,e)})}function m(){n={};o=0}var n={},o=0;setTimeout(q,25);return{flush:m,add:p,populate:q,load:function(h){if(!a.cacheLength||!o)return null;if(!a.url&&a.matchContains){var f=[],d;for(d in n)if(0<d.length){var m=n[d];c.each(m,function(a,c){b(c.value,h)&&f.push(c)})}return f}if(n[h])return n[h];if(a.matchSubset)for(d=h.length-1;d>=a.minChars;d--)if(m=n[h.substr(0,d)])return f=[],c.each(m,function(a,c){b(c.value,h)&&(f[f.length]=c)}),
f;return null}}};c.Autocompleter.Select=function(a,b,p,q){var m;function n(){l&&(k=c("<div/>").hide().addClass(a.resultsClass).css("position","absolute").appendTo(document.body),j=c("<ul/>").appendTo(k).mouseover(function(a){o(a).nodeName&&"LI"==o(a).nodeName.toUpperCase()&&(d=c("li",j).removeClass(m).index(o(a)),c(o(a)).addClass(m))}).click(function(a){c(o(a)).addClass(m);p();b.focus();return!1}).mousedown(function(){q.mouseDownOnSelect=!0}).mouseup(function(){q.mouseDownOnSelect=!1}),0<a.width&&
k.css("width",a.width),l=!1)}function o(a){for(a=a.target;a&&"LI"!=a.tagName;)a=a.parentNode;return!a?[]:a}function h(b){f.slice(d,d+1).removeClass(m);d+=b;0>d?d=f.size()-1:d>=f.size()&&(d=0);b=f.slice(d,d+1).addClass(m);if(a.scroll){var c=0;f.slice(0,d).each(function(){c+=this.offsetHeight});c+b[0].offsetHeight-j.scrollTop()>j[0].clientHeight?j.scrollTop(c+b[0].offsetHeight-j.innerHeight()):c<j.scrollTop()&&j.scrollTop(c)}}m="ac_over";var f,d=-1,r,g="",l=!0,k,j;return{display:function(b,h){n();r=
b;g=h;j.empty();for(var k=a.max&&a.max<r.length?a.max:r.length,i=0;i<k;i++)if(r[i]){var l=a.formatItem(r[i].data,i+1,k,r[i].value,g);!1!==l&&(l=c("<li/>").html(a.highlight(l,g)).addClass(0==i%2?"ac_even":"ac_odd").appendTo(j)[0],c.data(l,"ac_data",r[i]))}f=j.find("li");a.selectFirst&&(f.slice(0,1).addClass(m),d=0);c.fn.bgiframe&&j.bgiframe()},next:function(){h(1)},prev:function(){h(-1)},pageUp:function(){0!=d&&0>d-8?h(-d):h(-8)},pageDown:function(){d!=f.size()-1&&d+8>f.size()?h(f.size()-1-d):h(8)},
hide:function(){k&&k.hide();f&&f.removeClass(m);d=-1},visible:function(){return k&&k.is(":visible")},current:function(){return this.visible()&&(f.filter("."+m)[0]||a.selectFirst&&f[0])},show:function(){var e=c(b).offset();k.css({width:"string"==typeof a.width||0<a.width?a.width:c(b).width(),top:e.top+b.offsetHeight,left:e.left}).show();if(a.scroll&&(j.scrollTop(0),j.css({maxHeight:a.scrollHeight,overflow:"auto"}),c.browser.msie&&"undefined"===typeof document.body.style.maxHeight)){var d=0;f.each(function(){d+=
this.offsetHeight});e=d>a.scrollHeight;j.css("height",e?a.scrollHeight:d);e||f.width(j.width()-parseInt(f.css("padding-left"))-parseInt(f.css("padding-right")))}},selected:function(){var a=f&&f.filter("."+m).removeClass(m);return a&&a.length&&c.data(a[0],"ac_data")},emptyList:function(){j&&j.empty()},unbind:function(){k&&k.remove()}}};c.Autocompleter.Selection=function(a,b,c){if(a.setSelectionRange)a.setSelectionRange(b,c);else if(a.createTextRange){var q=a.createTextRange();q.collapse(!0);q.moveStart("character",
b);q.moveEnd("character",c);q.select()}else a.selectionStart&&(a.selectionStart=b,a.selectionEnd=c);a.focus()}})(jQuery);
//@ sourceMappingURL=osqa.admin.js.map